import { Injectable, inject } from '@angular/core';
import { RestService, Rest } from '@abp/ng.core';
import type { PagedResultDto } from '@abp/ng.core';
import type { WorkstationDto, CreateWorkstationDto } from '../../proxy/manufacturing/models';
import type { CompanyFilteredPagedRequestDto } from '../../proxy/shared/models';

/**
 * Manual proxy for WorkstationAppService which uses an explicit controller
 * ([RemoteService(false)] — not auto-generated by `abp generate-proxy`).
 */
@Injectable({ providedIn: 'root' })
export class WorkstationService {
  private restService = inject(RestService);
  apiName = 'Default';

  get = (id: string, config?: Partial<Rest.Config>) =>
    this.restService.request<any, WorkstationDto>({
      method: 'GET',
      url: `/api/app/manufacturing/workstations/${id}`,
    }, { apiName: this.apiName, ...config });

  getList = (input: CompanyFilteredPagedRequestDto, config?: Partial<Rest.Config>) =>
    this.restService.request<any, PagedResultDto<WorkstationDto>>({
      method: 'GET',
      url: '/api/app/manufacturing/workstations',
      params: { companyId: input.companyId, filter: input.filter, status: input.status, sorting: input.sorting, skipCount: input.skipCount, maxResultCount: input.maxResultCount },
    }, { apiName: this.apiName, ...config });

  create = (input: CreateWorkstationDto, config?: Partial<Rest.Config>) =>
    this.restService.request<any, WorkstationDto>({
      method: 'POST',
      url: '/api/app/manufacturing/workstations',
      body: input,
    }, { apiName: this.apiName, ...config });
}
