import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { PageModule } from '@abp/ng.components/page';
import { LocalizationPipe } from '@abp/ng.core';
import { ToasterService } from '@abp/ng.theme.shared';
import { LoadingOverlayComponent } from '../../shared/components/loading-overlay/loading-overlay.component';
import { DunningService } from '../../proxy/sales/dunning.service';
import { CompanyContextService } from '../../shared/services/company-context.service';
import type { DunningDto, AutoGenerateDunningsResultDto } from '../../proxy/sales/models';

import { PaginationComponent, type PageEvent } from '../../shared/components/pagination/pagination.component';

@Component({
  selector: 'app-dunning-list',
  standalone: true,
  imports: [PaginationComponent, CommonModule, FormsModule, RouterModule, PageModule, LocalizationPipe, LoadingOverlayComponent],
  template: `
    <abp-page [title]="'Dunnings' | abpLocalization">
      @if (isLoading) { <app-loading-overlay /> }

      <!-- Auto-Generate Dunnings panel -->
      <div class="card mb-3">
        <div class="card-body d-flex align-items-center gap-3 flex-wrap">
          <button class="btn btn-warning" (click)="showAutoGenerate.set(!showAutoGenerate())" [disabled]="isGenerating()">
            <i class="fa fa-wand-magic-sparkles me-1"></i>{{ '::AutoGenerateDunnings' | abpLocalization }}
          </button>
          @if (showAutoGenerate()) {
            <div class="d-flex align-items-end gap-2 flex-wrap">
              <div>
                <label class="form-label form-label-sm mb-0">{{ '::InterestRatePA' | abpLocalization }} (%)</label>
                <input type="number" class="form-control form-control-sm" [(ngModel)]="interestRate" style="width:100px" min="0" step="0.5" />
              </div>
              <div>
                <label class="form-label form-label-sm mb-0">{{ '::DunningFee' | abpLocalization }}</label>
                <input type="number" class="form-control form-control-sm" [(ngModel)]="dunningFee" style="width:100px" min="0" step="10" />
              </div>
              <button class="btn btn-success btn-sm" (click)="runAutoGenerate()" [disabled]="isGenerating()">
                @if (isGenerating()) { <span class="spinner-border spinner-border-sm me-1"></span> }
                <i class="fa fa-play me-1"></i>{{ '::Generate' | abpLocalization }}
              </button>
            </div>
          }
          @if (lastResult()) {
            <div class="ms-auto">
              <span class="badge bg-success me-1">{{ lastResult()!.createdCount }} {{ '::Created' | abpLocalization }}</span>
              @if (lastResult()!.skippedCount > 0) {
                <span class="badge bg-secondary me-1">{{ lastResult()!.skippedCount }} {{ '::Skipped' | abpLocalization }}</span>
              }
              @if (lastResult()!.failedCount > 0) {
                <span class="badge bg-danger">{{ lastResult()!.failedCount }} {{ '::Failed' | abpLocalization }}</span>
              }
            </div>
          }
        </div>
      </div>

      @if (!isLoading && items.length === 0) {
        <div class="text-center py-5">
          <i class="fa fa-bell fa-3x text-muted mb-3 d-block"></i>
          <p class="text-muted">{{ 'NoDunningsYet' | abpLocalization }}</p>
        </div>
      } @else if (!isLoading) {
        <div class="card"><div class="card-body">
          <table class="table table-hover mb-0">
            <thead><tr>
              <th>{{ 'Customer' | abpLocalization }}</th>
              <th>{{ 'Level' | abpLocalization }}</th>
              <th>{{ 'Date' | abpLocalization }}</th>
              <th class="text-end">{{ 'Outstanding' | abpLocalization }}</th>
              <th class="text-end">{{ 'GrandTotal' | abpLocalization }}</th>
              <th>{{ 'Status' | abpLocalization }}</th>
              <th>{{ '::Actions' | abpLocalization }}</th>
            </tr></thead>
            <tbody>
              @for (d of items; track d.id) {
                <tr>
                  <td>{{ d.customerName ?? '—' }}</td>
                  <td><span class="badge bg-warning">{{ 'Level' | abpLocalization }} {{ d.dunningLevel }}</span></td>
                  <td>{{ d.postingDate | date:'dd/MM/yyyy' }}</td>
                  <td class="text-end">{{ d.totalOutstanding | number:'1.2-2' }}</td>
                  <td class="text-end fw-bold">{{ d.grandTotal | number:'1.2-2' }}</td>
                  <td><span class="badge" [ngClass]="{'bg-secondary':d.status===0, 'bg-primary':d.status===1, 'bg-success':d.status===3, 'bg-danger':d.status===4}">
                    {{ ['Draft','Submitted','','Resolved','Cancelled'][d.status ?? 0] }}
                  </span></td>
                  <td><a [routerLink]="['/sales/dunnings', d.id]" class="btn btn-sm btn-outline-primary"><i class="fa fa-eye"></i></a></td>
                </tr>
              }
            </tbody>
          </table>
        </div></div>
      }
      <app-pagination [totalCount]="totalCount" [pageSize]="pageSize" [currentPage]="currentPage" (pageChange)="onPageChange($event)" />
  </abp-page>
  `,
})
export class DunningListComponent implements OnInit {
  private service = inject(DunningService);
  private companyContext = inject(CompanyContextService);
  private toaster = inject(ToasterService);

  items: DunningDto[] = [];
  isLoading = false;
  totalCount = 0;
  currentPage = 0;
  pageSize = 20;

  // Auto-generate state
  showAutoGenerate = signal(false);
  isGenerating = signal(false);
  lastResult = signal<any>(null);
  interestRate = 8; // Default 8% PA
  dunningFee = 0;

  ngOnInit(): void {
    this.load();
  }

  load(): void {
    this.isLoading = true;
    this.service.getList({ skipCount: this.currentPage * this.pageSize, maxResultCount: this.pageSize })
      .subscribe({ next: (r) => { this.items = r.items ?? []; this.totalCount = r.totalCount ?? 0; this.isLoading = false; }, error: () => { this.isLoading = false; } });
  }

  runAutoGenerate(): void {
    const companyId = this.companyContext.currentCompanyId();
    if (!companyId) {
      this.toaster.warn('::PleaseSelectCompanyFirst');
      return;
    }
    this.isGenerating.set(true);
    this.lastResult.set(null);
    this.service.autoGenerate({
      companyId,
      interestRatePerAnnum: this.interestRate,
      dunningFeePerCustomer: this.dunningFee,
    }).subscribe({
      next: (result) => {
        this.lastResult.set(result);
        this.isGenerating.set(false);
        if (result.createdCount > 0) {
          this.toaster.success('::DunningsAutoGenerated', result.createdCount.toString());
          this.load();
        } else {
          this.toaster.info('::NoOverdueInvoicesFound');
        }
      },
      error: () => {
        this.isGenerating.set(false);
        this.toaster.error('::OperationFailed');
      },
    });
  }

  onPageChange(event: PageEvent): void { this.currentPage = event.pageIndex; this.load(); }
}
