using System;
using System.Collections.Generic;
using MyERP.Shared;
using Volo.Abp.Application.Dtos;

namespace MyERP.Sales;

public class DunningDto : EntityDto<Guid>
{
    public Guid CompanyId { get; set; }
    public Guid CustomerId { get; set; }
    public string? CustomerName { get; set; }
    public DateTime PostingDate { get; set; }
    public int DunningLevel { get; set; }
    public decimal TotalOutstanding { get; set; }
    public decimal DunningFee { get; set; }
    public decimal InterestAmount { get; set; }
    public decimal GrandTotal { get; set; }
    public int Status { get; set; }
    public int OverduePaymentCount { get; set; }
    public DateTime? EmailSentAt { get; set; }
    public string? EmailSentTo { get; set; }

    /// <summary>Detailed overdue invoice entries (per ERPNext dunning_overdue_payment child table).</summary>
    public List<DunningOverduePaymentDto> OverduePayments { get; set; } = new();
}

/// <summary>Per-invoice detail in a Dunning (shows which invoices are overdue and by how much).</summary>
public class DunningOverduePaymentDto
{
    public Guid SalesInvoiceId { get; set; }
    public string? InvoiceNumber { get; set; }
    public decimal OutstandingAmount { get; set; }
    public DateTime DueDate { get; set; }
    public int OverdueDays { get; set; }
}

public class CreateDunningDto
{
    public Guid CompanyId { get; set; }
    public Guid CustomerId { get; set; }
    public string? CustomerName { get; set; }
    public DateTime PostingDate { get; set; }
    public decimal DunningFee { get; set; }
    public decimal InterestAmount { get; set; }
    /// <summary>Per-annum interest rate. If set and InterestAmount is 0, interest is auto-calculated.</summary>
    public decimal InterestRatePerAnnum { get; set; }
    public CreateDunningOverdueDto[] OverduePayments { get; set; } = [];
}

public class CreateDunningOverdueDto
{
    public Guid SalesInvoiceId { get; set; }
    public decimal OutstandingAmount { get; set; }
    public DateTime DueDate { get; set; }
    public int OverdueDays { get; set; }
}

public class SendDunningEmailDto
{
    public string? RecipientEmail { get; set; }
    public string? Cc { get; set; }
}

/// <summary>Input for batch auto-generating dunnings for all overdue customers in a company.</summary>
public class AutoGenerateDunningsDto
{
    public Guid CompanyId { get; set; }
    /// <summary>Date to evaluate overdue status against. Defaults to today if null.</summary>
    public DateTime? AsOfDate { get; set; }
    /// <summary>Annual interest rate (%) to apply on overdue amounts. 0 = no interest.</summary>
    public decimal InterestRatePerAnnum { get; set; }
    /// <summary>Flat fee to add per dunning document.</summary>
    public decimal DunningFeePerCustomer { get; set; }
}

/// <summary>Result of auto-generate dunnings batch operation.</summary>
public class AutoGenerateDunningsResultDto
{
    public int CustomersScanned { get; set; }
    public int CreatedCount { get; set; }
    public int SkippedCount { get; set; }
    public int FailedCount { get; set; }
    public decimal TotalOverdueAmount { get; set; }
}
