using System;
using System.Threading.Tasks;
using MyERP.Shared;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace MyERP.Sales;

public interface IDunningAppService : IApplicationService
{
    Task<PagedResultDto<DunningDto>> GetListAsync(CompanyFilteredPagedRequestDto input);
    Task<DunningDto> GetAsync(Guid id);
    Task<DunningDto> CreateAsync(CreateDunningDto input);
    Task<DunningDto> SubmitAsync(Guid id);
    Task<DunningDto> ResolveAsync(Guid id);
    Task<DunningDto> CancelAsync(Guid id);
    Task<AutoGenerateDunningsResultDto> AutoGenerateAsync(AutoGenerateDunningsDto input);
    Task SendDunningEmailAsync(Guid id, SendDunningEmailDto input);
}
