using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace MyERP.Sales;

public class PromotionalSchemeDto : EntityDto<Guid>
{
    public Guid CompanyId { get; set; }
    public string Title { get; set; } = null!;
    public bool IsDisabled { get; set; }
    public int ApplyOn { get; set; }
    public bool MixedConditions { get; set; }
    public bool IsCumulative { get; set; }
    public bool ApplyRuleOnOtherItem { get; set; }
    public int? OtherApplyOn { get; set; }
    public Guid? OtherTargetId { get; set; }
    public bool Selling { get; set; }
    public bool Buying { get; set; }
    public int ApplicableFor { get; set; }
    public DateTime? ValidFrom { get; set; }
    public DateTime? ValidUpto { get; set; }
    public Guid? CurrencyId { get; set; }

    public List<PromotionalSchemeTargetDto> Targets { get; set; } = new();
    public List<PromotionalSchemePartyDto> Parties { get; set; } = new();
    public List<PromotionalSchemePriceDiscountSlabDto> PriceDiscountSlabs { get; set; } = new();
    public List<PromotionalSchemeProductDiscountSlabDto> ProductDiscountSlabs { get; set; } = new();

    /// <summary>Count of Pricing Rules currently generated by this scheme.</summary>
    public int GeneratedRuleCount { get; set; }
}

public class PromotionalSchemeTargetDto
{
    public Guid TargetId { get; set; }
    public string? TargetName { get; set; }
}

public class PromotionalSchemePartyDto
{
    public Guid PartyId { get; set; }
    public string? PartyName { get; set; }
}

public class PromotionalSchemePriceDiscountSlabDto
{
    public int RateOrDiscount { get; set; }
    public decimal DiscountPercentage { get; set; }
    public decimal DiscountAmount { get; set; }
    public decimal Rate { get; set; }
    public decimal MinQty { get; set; }
    public decimal MaxQty { get; set; }
    public decimal MinAmount { get; set; }
    public decimal MaxAmount { get; set; }
    public int Priority { get; set; } = 1;
    public Guid? WarehouseId { get; set; }
    public string? Description { get; set; }
    public bool IsDisabled { get; set; }
}

public class PromotionalSchemeProductDiscountSlabDto
{
    public Guid FreeItemId { get; set; }
    public decimal FreeQty { get; set; }
    public decimal FreeItemRate { get; set; }
    public bool SameItem { get; set; }
    public decimal MinQty { get; set; }
    public decimal MaxQty { get; set; }
    public decimal MinAmount { get; set; }
    public decimal MaxAmount { get; set; }
    public int Priority { get; set; } = 1;
    public Guid? WarehouseId { get; set; }
    public string? Description { get; set; }
    public bool IsRecursive { get; set; }
    public decimal RecurseFor { get; set; }
    public bool RoundFreeQty { get; set; }
}

public class CreateUpdatePromotionalSchemeDto
{
    public Guid CompanyId { get; set; }
    public string Title { get; set; } = null!;
    public bool IsDisabled { get; set; }
    public PricingRuleApplyOn ApplyOn { get; set; } = PricingRuleApplyOn.ItemCode;
    public bool MixedConditions { get; set; }
    public bool IsCumulative { get; set; }
    public bool ApplyRuleOnOtherItem { get; set; }
    public PricingRuleApplyOn? OtherApplyOn { get; set; }
    public Guid? OtherTargetId { get; set; }
    public bool Selling { get; set; }
    public bool Buying { get; set; }
    public PromotionalSchemeApplicableFor ApplicableFor { get; set; } = PromotionalSchemeApplicableFor.None;
    public DateTime? ValidFrom { get; set; }
    public DateTime? ValidUpto { get; set; }
    public Guid? CurrencyId { get; set; }

    public List<PromotionalSchemeTargetDto> Targets { get; set; } = new();
    public List<PromotionalSchemePartyDto> Parties { get; set; } = new();
    public List<PromotionalSchemePriceDiscountSlabDto> PriceDiscountSlabs { get; set; } = new();
    public List<PromotionalSchemeProductDiscountSlabDto> ProductDiscountSlabs { get; set; } = new();
}
