using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MyERP.Sales.Entities;
using Volo.Abp.Domain.Repositories;
using Volo.Abp.Domain.Services;

namespace MyERP.Sales.DomainServices;

/// <summary>
/// Generates Pricing Rules from a Promotional Scheme's discount slabs, cross joined
/// against the scheme's apply-on targets and applicable-for parties.
///
/// Per ERPNext (promotional_scheme.py):
/// - One Pricing Rule per (target x party x slab) combination
/// - No targets selected (or ApplyOn == TransactionTotal) => single "no target" pass
/// - ApplicableFor == None (or no parties selected) => single "no party" pass
/// - Regeneration is idempotent: previously generated rules for the scheme are replaced
/// - Deleting the scheme cascades to delete its generated rules (on_trash)
///
/// Source: erpnext/accounts/doctype/promotional_scheme/promotional_scheme.py
/// </summary>
public class PromotionalSchemeService : DomainService
{
    private readonly IRepository<PricingRule, Guid> _pricingRuleRepository;

    public PromotionalSchemeService(IRepository<PricingRule, Guid> pricingRuleRepository)
    {
        _pricingRuleRepository = pricingRuleRepository;
    }

    /// <summary>Regenerates all Pricing Rules for this scheme (deletes previously generated ones first).</summary>
    public async Task RegeneratePricingRulesAsync(PromotionalScheme scheme)
    {
        scheme.Validate();

        await DeleteGeneratedRulesAsync(scheme.Id);

        var applicableFor = scheme.Selling && scheme.Buying ? "Both" : scheme.Selling ? "Selling" : "Buying";

        var targets = scheme.ApplyOn != PricingRuleApplyOn.TransactionTotal && scheme.Targets.Any()
            ? scheme.Targets.Select(t => ((Guid?)t.TargetId, t.TargetName)).ToList()
            : new List<(Guid?, string?)> { (null, null) };

        var parties = scheme.ApplicableFor != PromotionalSchemeApplicableFor.None && scheme.Parties.Any()
            ? scheme.Parties.Select(p => ((Guid?)p.PartyId, p.PartyName)).ToList()
            : new List<(Guid?, string?)> { (null, null) };

        foreach (var (targetId, targetName) in targets)
        {
            foreach (var (partyId, partyName) in parties)
            {
                foreach (var slab in scheme.PriceDiscountSlabs)
                {
                    var rule = BuildRule(scheme, applicableFor, targetId, targetName, partyId,
                        slab.RateOrDiscount, slab.IsDisabled);
                    rule.DiscountPercentage = slab.DiscountPercentage;
                    rule.DiscountAmount = slab.DiscountAmount;
                    rule.Rate = slab.Rate;
                    rule.MinQty = slab.MinQty;
                    rule.MaxQty = slab.MaxQty;
                    rule.MinAmount = slab.MinAmount;
                    rule.MaxAmount = slab.MaxAmount;
                    rule.Priority = slab.Priority;
                    rule.PromotionalSchemeSlabId = slab.Id;
                    await _pricingRuleRepository.InsertAsync(rule);
                }

                foreach (var slab in scheme.ProductDiscountSlabs)
                {
                    var rule = BuildRule(scheme, applicableFor, targetId, targetName, partyId,
                        PricingRuleType.FreeItem, false);
                    rule.FreeItemId = slab.SameItem ? targetId : slab.FreeItemId;
                    rule.FreeItemQty = slab.FreeQty;
                    rule.MinQty = slab.MinQty;
                    rule.MaxQty = slab.MaxQty;
                    rule.MinAmount = slab.MinAmount;
                    rule.MaxAmount = slab.MaxAmount;
                    rule.Priority = slab.Priority;
                    rule.PromotionalSchemeSlabId = slab.Id;
                    await _pricingRuleRepository.InsertAsync(rule);
                }
            }
        }
    }

    /// <summary>Deletes all Pricing Rules previously generated by the given scheme (on_trash cascade).</summary>
    public async Task DeleteGeneratedRulesAsync(Guid schemeId)
    {
        var query = await _pricingRuleRepository.GetQueryableAsync();
        var existing = query.Where(r => r.PromotionalSchemeId == schemeId).ToList();
        foreach (var rule in existing)
            await _pricingRuleRepository.DeleteAsync(rule);
    }

    private static PricingRule BuildRule(PromotionalScheme scheme, string applicableFor,
        Guid? targetId, string? targetName, Guid? partyId, PricingRuleType ruleType, bool slabDisabled)
    {
        var rule = new PricingRule(Guid.NewGuid(), scheme.Title, scheme.ApplyOn, ruleType, scheme.TenantId)
        {
            CompanyId = scheme.CompanyId,
            ApplicableFor = applicableFor,
            ApplyOnId = targetId,
            ApplyOnName = targetName,
            Priority = 1,
            ValidFrom = scheme.ValidFrom,
            ValidUpto = scheme.ValidUpto,
            PartyId = partyId,
            PartyType = scheme.ApplicableFor != PromotionalSchemeApplicableFor.None ? scheme.ApplicableFor.ToString() : null,
            IsDisabled = scheme.IsDisabled || slabDisabled,
            ApplyOnOtherItem = scheme.ApplyRuleOnOtherItem,
            OtherItemId = scheme.OtherTargetId,
            PromotionalSchemeId = scheme.Id,
        };
        return rule;
    }
}
