using System;
using System.Linq;
using System.Threading.Tasks;
using MyERP.Core;
using MyERP.HumanResources.Entities;
using MyERP.Permissions;
using MyERP.Shared;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;

namespace MyERP.HumanResources;

[Authorize(MyERPPermissions.Payroll.Default)]
public class SalarySlipAppService : ApplicationService, ISalarySlipAppService
{
    private readonly IRepository<SalarySlip, Guid> _repository;
    private readonly IRepository<Employee, Guid> _employeeRepository;

    public SalarySlipAppService(IRepository<SalarySlip, Guid> repository, IRepository<Employee, Guid> employeeRepository)
    {
        _repository = repository;
        _employeeRepository = employeeRepository;
    }

    public async Task<PagedResultDto<SalarySlipDto>> GetListAsync(CompanyFilteredPagedRequestDto input)
    {
        var query = await _repository.GetQueryableAsync();

        if (input.CompanyId.HasValue)
            query = query.Where(x => x.CompanyId == input.CompanyId.Value);

        if (!string.IsNullOrWhiteSpace(input.Filter))
        {
            var filter = input.Filter;
             query = query.Where(x => x.EmployeeName != null && x.EmployeeName.Contains(filter));
        }

        if (!string.IsNullOrWhiteSpace(input.Status) && Enum.TryParse<DocumentStatus>(input.Status, true, out var status))
            query = query.Where(x => x.Status == status);

        var totalCount = query.Count();
        var items = query.OrderByDescending(s => s.PostingDate)
            .Skip(input.SkipCount).Take(input.MaxResultCount).ToList();
        return new PagedResultDto<SalarySlipDto>(totalCount, items.Select(x => ObjectMapper.Map<SalarySlip, SalarySlipDto>(x)).ToList());
    }

    public async Task<SalarySlipDto> GetAsync(Guid id) => ObjectMapper.Map<SalarySlip, SalarySlipDto>(await _repository.GetAsync(id));

    /// <summary>Creates a one-off/adjustment Salary Slip (e.g. mid-cycle hire, bonus, correction) —
    /// independent of the bulk Payroll Entry run. Per ERPNext salary_slip.py, an individual
    /// Salary Slip can be created directly, not only generated by Payroll Entry.</summary>
    [Authorize(MyERPPermissions.Payroll.Create)]
    public async Task<SalarySlipDto> CreateAsync(CreateSalarySlipDto input)
    {
        var employee = await _employeeRepository.GetAsync(input.EmployeeId);

        var slip = new SalarySlip(GuidGenerator.Create(), input.CompanyId, input.EmployeeId,
            input.StartDate, input.EndDate, input.PostingDate, CurrentTenant.Id)
        {
            EmployeeName = employee.FullName,
            TotalWorkingDays = input.TotalWorkingDays,
            PaymentDays = input.PaymentDays,
            LeavesWithoutPay = input.LeavesWithoutPay,
        };
        ApplyComponents(slip, input);

        await _repository.InsertAsync(slip, autoSave: true);
        return ObjectMapper.Map<SalarySlip, SalarySlipDto>(slip);
    }

    [Authorize(MyERPPermissions.Payroll.Edit)]
    public async Task<SalarySlipDto> UpdateAsync(Guid id, CreateSalarySlipDto input)
    {
        var slip = await _repository.GetAsync(id);
        if (slip.Status != Core.DocumentStatus.Draft)
            throw new BusinessException(MyERPDomainErrorCodes.InvalidStatusTransition)
                .WithData("detail", "Only Draft salary slips can be edited");

        slip.PostingDate = input.PostingDate;
        slip.StartDate = input.StartDate;
        slip.EndDate = input.EndDate;
        slip.TotalWorkingDays = input.TotalWorkingDays;
        slip.PaymentDays = input.PaymentDays;
        slip.LeavesWithoutPay = input.LeavesWithoutPay;

        slip.ResetComponents();
        ApplyComponents(slip, input);

        await _repository.UpdateAsync(slip, autoSave: true);
        return ObjectMapper.Map<SalarySlip, SalarySlipDto>(slip);
    }

    private static void ApplyComponents(SalarySlip slip, CreateSalarySlipDto input)
    {
        foreach (var e in input.Earnings)
            slip.AddEarning(e.SalaryComponentId, e.ComponentName, e.Amount, e.IsStatutory);
        foreach (var d in input.Deductions)
            slip.AddDeduction(d.SalaryComponentId, d.ComponentName, d.Amount, d.IsStatutory);
    }

    [Authorize(MyERPPermissions.Payroll.Delete)]
    public async Task DeleteAsync(Guid id)
    {
        var slip = await _repository.GetAsync(id);
        if (slip.Status != Core.DocumentStatus.Draft)
            throw new BusinessException(MyERPDomainErrorCodes.InvalidStatusTransition)
                .WithData("detail", "Only Draft salary slips can be deleted");
        await _repository.DeleteAsync(id);
    }

    [Authorize(MyERPPermissions.Payroll.Submit)]
    public async Task<SalarySlipDto> SubmitAsync(Guid id)
    {
        var slip = await _repository.GetAsync(id);
        slip.Submit();
        await _repository.UpdateAsync(slip, autoSave: true);
        return ObjectMapper.Map<SalarySlip, SalarySlipDto>(slip);
    }

    [Authorize(MyERPPermissions.Payroll.Cancel)]
    public async Task<SalarySlipDto> CancelAsync(Guid id)
    {
        var slip = await _repository.GetAsync(id);
        slip.Cancel();
        await _repository.UpdateAsync(slip, autoSave: true);
        return ObjectMapper.Map<SalarySlip, SalarySlipDto>(slip);
    }
}

