import { authGuard, permissionGuard } from '@abp/ng.core';
import { Routes } from '@angular/router';
export const APP_ROUTES: Routes = [
  {
    path: '',
    pathMatch: 'full',
    loadComponent: () => import('./home/home.component').then(c => c.HomeComponent),
  },
  {
    path: 'account',
    loadChildren: () => import('@abp/ng.account').then(c => c.createRoutes()),
  },
  {
    path: 'identity',
    loadChildren: () => import('@abp/ng.identity').then(c => c.createRoutes()),
  },
  {
    path: 'tenant-management',
    loadChildren: () => import('@abp/ng.tenant-management').then(c => c.createRoutes()),
  },
  {
    path: 'setting-management',
    loadChildren: () => import('@abp/ng.setting-management').then(c => c.createRoutes()),
  },
  {
    path: 'companies',
    loadComponent: () => import('./companies/company-list.component').then(c => c.CompanyListComponent),
    canActivate: [authGuard, permissionGuard],
  },
  {
    path: 'customers',
    loadComponent: () => import('./customers/customer-list.component').then(c => c.CustomerListComponent),
    canActivate: [authGuard, permissionGuard],
  },
  {
    path: 'invoices',
    loadComponent: () => import('./invoices/invoice-list.component').then(c => c.InvoiceListComponent),
    canActivate: [authGuard, permissionGuard],
  },
  {
    path: 'sales/invoices',
    loadComponent: () => import('./sales/sales-invoices/sales-invoice-list.component').then(c => c.SalesInvoiceListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'sales/quotations',
    loadComponent: () => import('./sales/quotations/quotation-list.component').then(c => c.QuotationListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Quotations' },
  },
  {
    path: 'sales/quotations/new',
    loadComponent: () => import('./sales/quotations/quotation-form.component').then(c => c.QuotationFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Quotations.Create' },
  },
  {
    path: 'sales/orders',
    loadComponent: () => import('./sales/sales-orders/sales-order-list.component').then(c => c.SalesOrderListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesOrders' },
  },
  {
    path: 'sales/orders/new',
    loadComponent: () => import('./sales/sales-orders/sales-order-form.component').then(c => c.SalesOrderFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesOrders.Create' },
  },
  {
    path: 'sales/invoices/new',
    loadComponent: () => import('./sales/sales-invoices/sales-invoice-form.component').then(c => c.SalesInvoiceFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices.Create' },
  },
  {
    path: 'sales/invoices/:id',
    loadComponent: () => import('./sales/sales-invoices/sales-invoice-detail.component').then(c => c.SalesInvoiceDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'sales/invoices/:id/edit',
    loadComponent: () => import('./sales/sales-invoices/sales-invoice-form.component').then(c => c.SalesInvoiceFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices.Edit' },
  },
  {
    path: 'suppliers',
    loadComponent: () => import('./suppliers/supplier-list.component').then(c => c.SupplierListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Suppliers' },
  },
  {
    path: 'e-invoice/dashboard',
    loadComponent: () => import('./e-invoice/dashboard/lhdn-dashboard.component').then(c => c.LhdnDashboardComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.EInvoice' },
  },
  {
    path: 'purchasing/invoices',
    loadComponent: () => import('./purchasing/purchase-invoices/purchase-invoice-list.component').then(c => c.PurchaseInvoiceListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseInvoices' },
  },
  {
    path: 'purchasing/invoices/new',
    loadComponent: () => import('./purchasing/purchase-invoices/purchase-invoice-form.component').then(c => c.PurchaseInvoiceFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseInvoices.Create' },
  },
  {
    path: 'purchasing/invoices/:id/edit',
    loadComponent: () => import('./purchasing/purchase-invoices/purchase-invoice-form.component').then(c => c.PurchaseInvoiceFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseInvoices.Edit' },
  },
  {
    path: 'accounting/accounts',
    loadComponent: () => import('./accounting/accounts/chart-of-accounts.component').then(c => c.ChartOfAccountsComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'accounting/journal-entries/new',
    loadComponent: () => import('./accounting/journal-entries/journal-entry-form.component').then(c => c.JournalEntryFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.JournalEntries.Create' },
  },
  {
    path: 'inventory/items',
    loadComponent: () => import('./inventory/items/item-list.component').then(c => c.ItemListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Items' },
  },
  {
    path: 'accounting/reports/trial-balance',
    loadComponent: () => import('./accounting/reports/trial-balance/trial-balance.component').then(c => c.TrialBalanceComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'accounting/reports/profit-loss',
    loadComponent: () => import('./accounting/reports/profit-loss/profit-loss.component').then(c => c.ProfitLossComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'accounting/payments/new',
    loadComponent: () => import('./accounting/payments/payment-entry-form.component').then(c => c.PaymentEntryFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PaymentEntries.Create' },
  },
  {
    path: 'accounting/reports/balance-sheet',
    loadComponent: () => import('./accounting/reports/balance-sheet/balance-sheet.component').then(c => c.BalanceSheetComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'inventory/warehouses',
    loadComponent: () => import('./inventory/warehouses/warehouse-list.component').then(c => c.WarehouseListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Warehouses' },
  },
  {
    path: 'inventory/stock-entries/new',
    loadComponent: () => import('./inventory/stock-entries/stock-entry-form.component').then(c => c.StockEntryFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.StockEntries.Create' },
  },
  {
    path: 'e-invoice/logs',
    loadComponent: () => import('./e-invoice/logs/einvoice-logs.component').then(c => c.EinvoiceLogsComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.EInvoice' },
  },
  {
    path: 'sales/delivery-notes',
    loadComponent: () => import('./sales/delivery-notes/delivery-note-list.component').then(c => c.DeliveryNoteListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.DeliveryNotes' },
  },
  {
    path: 'sales/pos',
    loadComponent: () => import('./sales/pos/pos.component').then(c => c.PosComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.POS' },
  },
  {
    path: 'purchasing/receipts',
    loadComponent: () => import('./purchasing/purchase-receipts/purchase-receipt-list.component').then(c => c.PurchaseReceiptListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseReceipts' },
  },
  {
    path: 'inventory/reports/stock-ledger',
    loadComponent: () => import('./inventory/reports/stock-ledger/stock-ledger-report.component').then(c => c.StockLedgerReportComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.StockLedger' },
  },
  {
    path: 'accounting/bank-reconciliation',
    loadComponent: () => import('./accounting/bank-reconciliation/bank-reconciliation.component').then(c => c.BankReconciliationComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.BankReconciliation' },
  },
  {
    path: 'e-invoice/reports',
    loadComponent: () => import('./e-invoice/reports/einvoice-status-report.component').then(c => c.EinvoiceStatusReportComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.EInvoice' },
  },
];
