import { authGuard, permissionGuard } from '@abp/ng.core';
import { Routes } from '@angular/router';
export const APP_ROUTES: Routes = [
  {
    path: '',
    pathMatch: 'full',
    loadComponent: () => import('./home/home.component').then(c => c.HomeComponent),
  },
  {
    path: 'account',
    loadChildren: () => import('@abp/ng.account').then(c => c.createRoutes()),
  },
  {
    path: 'identity',
    loadChildren: () => import('@abp/ng.identity').then(c => c.createRoutes()),
  },
  {
    path: 'tenant-management',
    loadChildren: () => import('@abp/ng.tenant-management').then(c => c.createRoutes()),
  },
  {
    path: 'setting-management',
    loadChildren: () => import('@abp/ng.setting-management').then(c => c.createRoutes()),
  },
  {
    path: 'companies',
    loadComponent: () => import('./companies/company-list.component').then(c => c.CompanyListComponent),
    canActivate: [authGuard, permissionGuard],
  },
  {
    path: 'companies/new',
    loadComponent: () => import('./companies/company-form.component').then(c => c.CompanyFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Companies.Create' },
  },
  {
    path: 'companies/:id/edit',
    loadComponent: () => import('./companies/company-form.component').then(c => c.CompanyFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Companies.Edit' },
  },
  {
    path: 'customers',
    loadComponent: () => import('./customers/customer-list.component').then(c => c.CustomerListComponent),
    canActivate: [authGuard, permissionGuard],
  },
  {
    path: 'customers/new',
    loadComponent: () => import('./customers/customer-form.component').then(c => c.CustomerFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Customers.Create' },
  },
  {
    path: 'customers/:id/edit',
    loadComponent: () => import('./customers/customer-form.component').then(c => c.CustomerFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Customers.Edit' },
  },
  {
    path: 'invoices',
    loadComponent: () => import('./invoices/invoice-list.component').then(c => c.InvoiceListComponent),
    canActivate: [authGuard, permissionGuard],
  },
  {
    path: 'sales/invoices',
    loadComponent: () => import('./sales/sales-invoices/sales-invoice-list.component').then(c => c.SalesInvoiceListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'sales/quotations',
    loadComponent: () => import('./sales/quotations/quotation-list.component').then(c => c.QuotationListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Quotations' },
  },
  {
    path: 'sales/quotations/new',
    loadComponent: () => import('./sales/quotations/quotation-form.component').then(c => c.QuotationFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Quotations.Create' },
  },
  {
    path: 'sales/quotations/:id',
    loadComponent: () => import('./sales/quotations/quotation-detail.component').then(c => c.QuotationDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Quotations' },
  },
  {
    path: 'sales/orders',
    loadComponent: () => import('./sales/sales-orders/sales-order-list.component').then(c => c.SalesOrderListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesOrders' },
  },
  {
    path: 'sales/orders/new',
    loadComponent: () => import('./sales/sales-orders/sales-order-form.component').then(c => c.SalesOrderFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesOrders.Create' },
  },
  {
    path: 'sales/orders/:id',
    loadComponent: () => import('./sales/sales-orders/sales-order-detail.component').then(c => c.SalesOrderDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesOrders' },
  },
  {
    path: 'sales/invoices/new',
    loadComponent: () => import('./sales/sales-invoices/sales-invoice-form.component').then(c => c.SalesInvoiceFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices.Create' },
  },
  {
    path: 'sales/invoices/:id',
    loadComponent: () => import('./sales/sales-invoices/sales-invoice-detail.component').then(c => c.SalesInvoiceDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'sales/invoices/:id/edit',
    loadComponent: () => import('./sales/sales-invoices/sales-invoice-form.component').then(c => c.SalesInvoiceFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices.Edit' },
  },
  {
    path: 'suppliers',
    loadComponent: () => import('./suppliers/supplier-list.component').then(c => c.SupplierListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Suppliers' },
  },
  {
    path: 'suppliers/new',
    loadComponent: () => import('./suppliers/supplier-form.component').then(c => c.SupplierFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Suppliers.Create' },
  },
  {
    path: 'suppliers/:id/edit',
    loadComponent: () => import('./suppliers/supplier-form.component').then(c => c.SupplierFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Suppliers.Edit' },
  },
  {
    path: 'e-invoice/dashboard',
    loadComponent: () => import('./e-invoice/dashboard/lhdn-dashboard.component').then(c => c.LhdnDashboardComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.EInvoice' },
  },
  {
    path: 'purchasing/orders',
    loadComponent: () => import('./purchasing/purchase-orders/purchase-order-list.component').then(c => c.PurchaseOrderListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseOrders' },
  },
  {
    path: 'purchasing/orders/new',
    loadComponent: () => import('./purchasing/purchase-orders/purchase-order-form.component').then(c => c.PurchaseOrderFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseOrders.Create' },
  },
  {
    path: 'purchasing/orders/:id',
    loadComponent: () => import('./purchasing/purchase-orders/purchase-order-detail.component').then(c => c.PurchaseOrderDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseOrders' },
  },
  {
    path: 'purchasing/invoices',
    loadComponent: () => import('./purchasing/purchase-invoices/purchase-invoice-list.component').then(c => c.PurchaseInvoiceListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseInvoices' },
  },
  {
    path: 'purchasing/invoices/new',
    loadComponent: () => import('./purchasing/purchase-invoices/purchase-invoice-form.component').then(c => c.PurchaseInvoiceFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseInvoices.Create' },
  },
  {
    path: 'purchasing/invoices/:id/edit',
    loadComponent: () => import('./purchasing/purchase-invoices/purchase-invoice-form.component').then(c => c.PurchaseInvoiceFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseInvoices.Edit' },
  },
  {
    path: 'purchasing/invoices/:id',
    loadComponent: () => import('./purchasing/purchase-invoices/purchase-invoice-detail.component').then(c => c.PurchaseInvoiceDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseInvoices' },
  },
  {
    path: 'accounting/accounts',
    loadComponent: () => import('./accounting/accounts/chart-of-accounts.component').then(c => c.ChartOfAccountsComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'accounting/accounts/new',
    loadComponent: () => import('./accounting/accounts/account-form.component').then(c => c.AccountFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts.Create' },
  },
  {
    path: 'accounting/accounts/:id/edit',
    loadComponent: () => import('./accounting/accounts/account-form.component').then(c => c.AccountFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts.Edit' },
  },
  {
    path: 'accounting/journal-entries/new',
    loadComponent: () => import('./accounting/journal-entries/journal-entry-form.component').then(c => c.JournalEntryFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.JournalEntries.Create' },
  },
  {
    path: 'accounting/journal-entries',
    loadComponent: () => import('./accounting/journal-entries/journal-entry-list.component').then(c => c.JournalEntryListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.JournalEntries' },
  },
  {
    path: 'inventory/items',
    loadComponent: () => import('./inventory/items/item-list.component').then(c => c.ItemListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Items' },
  },
  {
    path: 'accounting/reports/trial-balance',
    loadComponent: () => import('./accounting/reports/trial-balance/trial-balance.component').then(c => c.TrialBalanceComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'accounting/reports/profit-loss',
    loadComponent: () => import('./accounting/reports/profit-loss/profit-loss.component').then(c => c.ProfitLossComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'accounting/payments',
    loadComponent: () => import('./accounting/payments/payment-entry-list.component').then(c => c.PaymentEntryListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PaymentEntries' },
  },
  {
    path: 'accounting/payments/new',
    loadComponent: () => import('./accounting/payments/payment-entry-form.component').then(c => c.PaymentEntryFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PaymentEntries.Create' },
  },
  {
    path: 'accounting/reports/balance-sheet',
    loadComponent: () => import('./accounting/reports/balance-sheet/balance-sheet.component').then(c => c.BalanceSheetComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'inventory/warehouses',
    loadComponent: () => import('./inventory/warehouses/warehouse-list.component').then(c => c.WarehouseListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Warehouses' },
  },
  {
    path: 'inventory/warehouses/new',
    loadComponent: () => import('./inventory/warehouses/warehouse-form.component').then(c => c.WarehouseFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Warehouses.Create' },
  },
  {
    path: 'inventory/warehouses/:id/edit',
    loadComponent: () => import('./inventory/warehouses/warehouse-form.component').then(c => c.WarehouseFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Warehouses.Edit' },
  },
  {
    path: 'inventory/stock-entries/new',
    loadComponent: () => import('./inventory/stock-entries/stock-entry-form.component').then(c => c.StockEntryFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.StockEntries.Create' },
  },
  {
    path: 'inventory/stock-entries',
    loadComponent: () => import('./inventory/stock-entries/stock-entry-list.component').then(c => c.StockEntryListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.StockEntries' },
  },
  {
    path: 'inventory/reports/stock-ledger',
    loadComponent: () => import('./inventory/reports/stock-ledger/stock-ledger.component').then(c => c.StockLedgerComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Items' },
  },
  {
    path: 'inventory/items/new',
    loadComponent: () => import('./inventory/items/item-form.component').then(c => c.ItemFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Items.Create' },
  },
  {
    path: 'inventory/items/:id/edit',
    loadComponent: () => import('./inventory/items/item-form.component').then(c => c.ItemFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Items.Edit' },
  },
  {
    path: 'e-invoice/logs',
    loadComponent: () => import('./e-invoice/logs/einvoice-logs.component').then(c => c.EinvoiceLogsComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.EInvoice' },
  },
  {
    path: 'sales/delivery-notes',
    loadComponent: () => import('./sales/delivery-notes/delivery-note-list.component').then(c => c.DeliveryNoteListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.DeliveryNotes' },
  },
  {
    path: 'sales/delivery-notes/new',
    loadComponent: () => import('./sales/delivery-notes/delivery-note-form.component').then(c => c.DeliveryNoteFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.DeliveryNotes.Create' },
  },
  {
    path: 'sales/delivery-notes/:id',
    loadComponent: () => import('./sales/delivery-notes/delivery-note-detail.component').then(c => c.DeliveryNoteDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.DeliveryNotes' },
  },
  {
    path: 'sales/pos',
    loadComponent: () => import('./sales/pos/pos.component').then(c => c.PosComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.POS' },
  },
  {
    path: 'purchasing/receipts',
    loadComponent: () => import('./purchasing/purchase-receipts/purchase-receipt-list.component').then(c => c.PurchaseReceiptListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseReceipts' },
  },
  {
    path: 'purchasing/receipts/new',
    loadComponent: () => import('./purchasing/purchase-receipts/purchase-receipt-form.component').then(c => c.PurchaseReceiptFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseReceipts' },
  },
  {
    path: 'purchasing/receipts/:id',
    loadComponent: () => import('./purchasing/purchase-receipts/purchase-receipt-detail.component').then(c => c.PurchaseReceiptDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseReceipts' },
  },
  {
    path: 'inventory/reports/stock-ledger',
    loadComponent: () => import('./inventory/reports/stock-ledger/stock-ledger-report.component').then(c => c.StockLedgerReportComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.StockLedger' },
  },
  {
    path: 'accounting/bank-reconciliation',
    loadComponent: () => import('./accounting/bank-reconciliation/bank-reconciliation.component').then(c => c.BankReconciliationComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.BankReconciliation' },
  },
  {
    path: 'e-invoice/reports',
    loadComponent: () => import('./e-invoice/reports/einvoice-status-report.component').then(c => c.EinvoiceStatusReportComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.EInvoice' },
  },
  {
    path: 'workflow/pending',
    loadComponent: () => import('./workflow/pending-approvals/pending-approvals.component').then(c => c.PendingApprovalsComponent),
    canActivate: [authGuard, permissionGuard],
  },
  {
    path: 'workflow/rules',
    loadComponent: () => import('./workflow/approval-rules/approval-rules-list.component').then(c => c.ApprovalRulesListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.ApprovalWorkflows' },
  },
  {
    path: 'workflow/rules/new',
    loadComponent: () => import('./workflow/approval-rules/approval-rule-form.component').then(c => c.ApprovalRuleFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.ApprovalWorkflows' },
  },
  {
    path: 'import-export',
    loadComponent: () => import('./import-export/import-export.component').then(c => c.ImportExportComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.ImportExport' },
  },
  {
    path: 'automation',
    loadComponent: () => import('./automation/automation-rules/automation-rule-list.component').then(c => c.AutomationRuleListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.AutomationRules' },
  },
  {
    path: 'automation/new',
    loadComponent: () => import('./automation/automation-rules/automation-rule-form.component').then(c => c.AutomationRuleFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.AutomationRules.Create' },
  },
  {
    path: 'hr/employees',
    loadComponent: () => import('./hr/employees/employee-list.component').then(c => c.EmployeeListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Employees' },
  },
  {
    path: 'hr/employees/new',
    loadComponent: () => import('./hr/employees/employee-form.component').then(c => c.EmployeeFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Employees.Create' },
  },
  {
    path: 'hr/employees/:id/edit',
    loadComponent: () => import('./hr/employees/employee-form.component').then(c => c.EmployeeFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Employees.Edit' },
  },
  {
    path: 'hr/payroll',
    loadComponent: () => import('./hr/payroll/payroll-list.component').then(c => c.PayrollListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Employees' },
  },
  {
    path: 'hr/payroll/:id',
    loadComponent: () => import('./hr/payroll/payroll-detail.component').then(c => c.PayrollDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Employees' },
  },
  {
    path: 'tax/categories',
    loadComponent: () => import('./tax/tax-categories/tax-categories.component').then(c => c.TaxCategoriesComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.TaxCategories' },
  },
  // CRM
  {
    path: 'crm/leads',
    loadComponent: () => import('./crm/leads/lead-list.component').then(c => c.LeadListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Leads' },
  },
  {
    path: 'crm/leads/new',
    loadComponent: () => import('./crm/leads/lead-form.component').then(c => c.LeadFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Leads.Create' },
  },
  {
    path: 'crm/leads/:id/edit',
    loadComponent: () => import('./crm/leads/lead-form.component').then(c => c.LeadFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Leads.Edit' },
  },
  {
    path: 'crm/leads/:id',
    loadComponent: () => import('./crm/leads/lead-detail.component').then(c => c.LeadDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Leads' },
  },
  {
    path: 'crm/opportunities',
    loadComponent: () => import('./crm/opportunities/opportunity-list.component').then(c => c.OpportunityListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Opportunities' },
  },
  {
    path: 'crm/opportunities/new',
    loadComponent: () => import('./crm/opportunities/opportunity-form.component').then(c => c.OpportunityFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Opportunities.Create' },
  },
  {
    path: 'crm/opportunities/:id',
    loadComponent: () => import('./crm/opportunities/opportunity-list.component').then(c => c.OpportunityListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Opportunities' },
  },
  {
    path: 'crm/opportunities/:id/edit',
    loadComponent: () => import('./crm/opportunities/opportunity-form.component').then(c => c.OpportunityFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Opportunities.Edit' },
  },
  // Projects
  {
    path: 'projects',
    loadComponent: () => import('./projects/project-list/project-list.component').then(c => c.ProjectListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Projects' },
  },
  {
    path: 'projects/new',
    loadComponent: () => import('./projects/project-list/project-list.component').then(c => c.ProjectListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Projects.Create' },
  },
  {
    path: 'projects/:id',
    loadComponent: () => import('./projects/project-list/project-list.component').then(c => c.ProjectListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Projects' },
  },
  {
    path: 'projects/:id/edit',
    loadComponent: () => import('./projects/project-list/project-list.component').then(c => c.ProjectListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Projects.Edit' },
  },
  // Assets
  {
    path: 'assets',
    loadComponent: () => import('./assets/asset-list/asset-list.component').then(c => c.AssetListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Assets' },
  },
  {
    path: 'assets/new',
    loadComponent: () => import('./assets/asset-list/asset-list.component').then(c => c.AssetListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Assets.Create' },
  },
  {
    path: 'assets/:id',
    loadComponent: () => import('./assets/asset-list/asset-list.component').then(c => c.AssetListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Assets' },
  },
  // Manufacturing
  {
    path: 'manufacturing/work-orders',
    loadComponent: () => import('./manufacturing/work-orders/work-order-list.component').then(c => c.WorkOrderListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Manufacturing' },
  },
  {
    path: 'manufacturing/work-orders/new',
    loadComponent: () => import('./manufacturing/work-orders/work-order-form.component').then(c => c.WorkOrderFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Manufacturing.Create' },
  },
  {
    path: 'manufacturing/work-orders/:id',
    loadComponent: () => import('./manufacturing/work-orders/work-order-list.component').then(c => c.WorkOrderListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Manufacturing' },
  }];
