import { authGuard, permissionGuard } from '@abp/ng.core';
import { Routes } from '@angular/router';
export const APP_ROUTES: Routes = [
  {
    path: '',
    pathMatch: 'full',
    loadComponent: () => import('./home/home.component').then(c => c.HomeComponent),
  },
  {
    path: 'account',
    loadChildren: () => import('@abp/ng.account').then(c => c.createRoutes()),
  },
  {
    path: 'identity',
    loadChildren: () => import('@abp/ng.identity').then(c => c.createRoutes()),
  },
  {
    path: 'tenant-management',
    loadChildren: () => import('@abp/ng.tenant-management').then(c => c.createRoutes()),
  },
  {
    path: 'setting-management',
    loadChildren: () => import('@abp/ng.setting-management').then(c => c.createRoutes()),
  },
  {
    path: 'companies',
    loadComponent: () => import('./companies/company-list.component').then(c => c.CompanyListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Companies' },
  },
  {
    path: 'companies/new',
    loadComponent: () => import('./companies/company-form.component').then(c => c.CompanyFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Companies.Create' },
  },
  {
    path: 'companies/:id/edit',
    loadComponent: () => import('./companies/company-form.component').then(c => c.CompanyFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Companies.Edit' },
  },
  {
    path: 'customers',
    loadComponent: () => import('./customers/customer-list.component').then(c => c.CustomerListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Customers' },
  },
  {
    path: 'customers/new',
    loadComponent: () => import('./customers/customer-form.component').then(c => c.CustomerFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Customers.Create' },
  },
  {
    path: 'customers/:id/edit',
    loadComponent: () => import('./customers/customer-form.component').then(c => c.CustomerFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Customers.Edit' },
  },
  {
    path: 'sales/invoices',
    loadComponent: () => import('./sales/sales-invoices/sales-invoice-list.component').then(c => c.SalesInvoiceListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'sales/quotations',
    loadComponent: () => import('./sales/quotations/quotation-list.component').then(c => c.QuotationListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Quotations' },
  },
  {
    path: 'sales/quotations/new',
    loadComponent: () => import('./sales/quotations/quotation-form.component').then(c => c.QuotationFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Quotations.Create' },
  },
  {
    path: 'sales/quotations/:id',
    loadComponent: () => import('./sales/quotations/quotation-detail.component').then(c => c.QuotationDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Quotations' },
  },
  {
    path: 'sales/orders',
    loadComponent: () => import('./sales/sales-orders/sales-order-list.component').then(c => c.SalesOrderListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesOrders' },
  },
  {
    path: 'sales/orders/new',
    loadComponent: () => import('./sales/sales-orders/sales-order-form.component').then(c => c.SalesOrderFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.SalesOrders.Create' },
  },
  {
    path: 'sales/orders/:id',
    loadComponent: () => import('./sales/sales-orders/sales-order-detail.component').then(c => c.SalesOrderDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesOrders' },
  },
  {
    path: 'sales/invoices/new',
    loadComponent: () => import('./sales/sales-invoices/sales-invoice-form.component').then(c => c.SalesInvoiceFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.SalesInvoices.Create' },
  },
  {
    path: 'sales/invoices/:id',
    loadComponent: () => import('./sales/sales-invoices/sales-invoice-detail.component').then(c => c.SalesInvoiceDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'sales/invoices/:id/edit',
    loadComponent: () => import('./sales/sales-invoices/sales-invoice-form.component').then(c => c.SalesInvoiceFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.SalesInvoices.Edit' },
  },
  {
    path: 'suppliers',
    loadComponent: () => import('./suppliers/supplier-list.component').then(c => c.SupplierListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Suppliers' },
  },
  {
    path: 'suppliers/new',
    loadComponent: () => import('./suppliers/supplier-form.component').then(c => c.SupplierFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Suppliers.Create' },
  },
  {
    path: 'suppliers/:id/edit',
    loadComponent: () => import('./suppliers/supplier-form.component').then(c => c.SupplierFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Suppliers.Edit' },
  },
  {
    path: 'e-invoice/dashboard',
    loadComponent: () => import('./e-invoice/dashboard/lhdn-dashboard.component').then(c => c.LhdnDashboardComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.EInvoice' },
  },
  {
    path: 'purchasing/orders',
    loadComponent: () => import('./purchasing/purchase-orders/purchase-order-list.component').then(c => c.PurchaseOrderListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseOrders' },
  },
  {
    path: 'purchasing/orders/new',
    loadComponent: () => import('./purchasing/purchase-orders/purchase-order-form.component').then(c => c.PurchaseOrderFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.PurchaseOrders.Create' },
  },
  {
    path: 'purchasing/orders/:id',
    loadComponent: () => import('./purchasing/purchase-orders/purchase-order-detail.component').then(c => c.PurchaseOrderDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseOrders' },
  },
  {
    path: 'purchasing/invoices',
    loadComponent: () => import('./purchasing/purchase-invoices/purchase-invoice-list.component').then(c => c.PurchaseInvoiceListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseInvoices' },
  },
  {
    path: 'purchasing/invoices/new',
    loadComponent: () => import('./purchasing/purchase-invoices/purchase-invoice-form.component').then(c => c.PurchaseInvoiceFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.PurchaseInvoices.Create' },
  },
  {
    path: 'purchasing/invoices/:id/edit',
    loadComponent: () => import('./purchasing/purchase-invoices/purchase-invoice-form.component').then(c => c.PurchaseInvoiceFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.PurchaseInvoices.Edit' },
  },
  {
    path: 'purchasing/invoices/:id',
    loadComponent: () => import('./purchasing/purchase-invoices/purchase-invoice-detail.component').then(c => c.PurchaseInvoiceDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseInvoices' },
  },
  {
    path: 'accounting/accounts',
    loadComponent: () => import('./accounting/accounts/chart-of-accounts.component').then(c => c.ChartOfAccountsComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'accounting/accounts/new',
    loadComponent: () => import('./accounting/accounts/account-form.component').then(c => c.AccountFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Accounts.Create' },
  },
  {
    path: 'accounting/accounts/:id/edit',
    loadComponent: () => import('./accounting/accounts/account-form.component').then(c => c.AccountFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Accounts.Edit' },
  },
  {
    path: 'accounting/journal-entries/new',
    loadComponent: () => import('./accounting/journal-entries/journal-entry-form.component').then(c => c.JournalEntryFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.JournalEntries.Create' },
  },
  {
    path: 'accounting/journal-entries',
    loadComponent: () => import('./accounting/journal-entries/journal-entry-list.component').then(c => c.JournalEntryListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.JournalEntries' },
  },
  {
    path: 'inventory/items',
    loadComponent: () => import('./inventory/items/item-list.component').then(c => c.ItemListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Items' },
  },
  {
    path: 'accounting/reports/trial-balance',
    loadComponent: () => import('./accounting/reports/trial-balance/trial-balance.component').then(c => c.TrialBalanceComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'accounting/reports/profit-loss',
    loadComponent: () => import('./accounting/reports/profit-loss/profit-loss.component').then(c => c.ProfitLossComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'accounting/payments',
    loadComponent: () => import('./accounting/payments/payment-entry-list.component').then(c => c.PaymentEntryListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PaymentEntries' },
  },
  {
    path: 'accounting/payments/new',
    loadComponent: () => import('./accounting/payments/payment-entry-form.component').then(c => c.PaymentEntryFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.PaymentEntries.Create' },
  },
  {
    path: 'accounting/payments/:id',
    loadComponent: () => import('./accounting/payments/payment-entry-detail.component').then(c => c.PaymentEntryDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PaymentEntries' },
  },
  {
    path: 'accounting/reports/balance-sheet',
    loadComponent: () => import('./accounting/reports/balance-sheet/balance-sheet.component').then(c => c.BalanceSheetComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'accounting/reports/aging',
    loadComponent: () => import('./accounting/reports/aging-report/aging-report.component').then(c => c.AgingReportComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'accounting/reports/general-ledger',
    loadComponent: () => import('./accounting/reports/general-ledger/general-ledger.component').then(c => c.GeneralLedgerComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'accounting/reports/outstanding',
    loadComponent: () => import('./accounting/outstanding-invoices/outstanding-invoices.component').then(c => c.OutstandingInvoicesComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'accounting/reports/party-ledger',
    loadComponent: () => import('./accounting/party-ledger/party-ledger.component').then(c => c.PartyLedgerComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'accounting/reports/statement-of-accounts',
    loadComponent: () => import('./accounting/statement-of-accounts/statement-of-accounts.component').then(c => c.StatementOfAccountsComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'sales/reports/gross-profit',
    loadComponent: () => import('./sales/reports/gross-profit-report/gross-profit-report.component').then(c => c.GrossProfitReportComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'sales/reports/register',
    loadComponent: () => import('./sales/reports/sales-register/sales-register.component').then(c => c.SalesRegisterComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'sales/reports/item-sales',
    loadComponent: () => import('./sales/reports/item-sales-report/item-sales-report.component').then(c => c.ItemSalesReportComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'sales/reports/customer-revenue',
    loadComponent: () => import('./sales/reports/customer-revenue-report/customer-revenue-report.component').then(c => c.CustomerRevenueReportComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'purchasing/reports/register',
    loadComponent: () => import('./purchasing/reports/purchase-register/purchase-register.component').then(c => c.PurchaseRegisterComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseInvoices' },
  },
  {
    path: 'settings',
    loadComponent: () => import('./settings/settings-overview/settings-overview.component').then(c => c.SettingsOverviewComponent),
    canActivate: [authGuard],
  },
  {
    path: 'settings/email-templates',
    loadComponent: () => import('./settings/email-templates/email-template-list.component').then(c => c.EmailTemplateListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.AutomationRules' },
  },
  {
    path: 'settings/company',
    loadComponent: () => import('./settings/company-settings/company-settings.component').then(c => c.CompanySettingsComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Companies.Edit' },
  },
  {
    path: 'settings/authorization-rules',
    loadComponent: () => import('./settings/authorization-rules/authorization-rule-list.component').then(c => c.AuthorizationRuleListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.ApprovalWorkflows' },
  },
  {
    path: 'manufacturing/settings',
    loadComponent: () => import('./manufacturing/settings/manufacturing-settings.component').then(c => c.ManufacturingSettingsComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Manufacturing' },
  },
  {
    path: 'settings/notification-logs',
    loadComponent: () => import('./settings/notification-logs/notification-log-list.component').then(c => c.NotificationLogListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.AutomationRules' },
  },
  {
    path: 'sales/installation-notes',
    loadComponent: () => import('./sales/installation-notes/installation-note-list.component').then(c => c.InstallationNoteListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.DeliveryNotes' },
  },
  {
    path: 'assets/capitalizations',
    loadComponent: () => import('./assets/capitalizations/asset-capitalization-list.component').then(c => c.AssetCapitalizationListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Assets' },
  },
  {
    path: 'accounting/budgets',
    loadComponent: () => import('./accounting/budgets/budget-list.component').then(c => c.BudgetListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Budgets' },
  },
  {
    path: 'inventory/warehouses',
    loadComponent: () => import('./inventory/warehouses/warehouse-list.component').then(c => c.WarehouseListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Warehouses' },
  },
  {
    path: 'inventory/warehouses/new',
    loadComponent: () => import('./inventory/warehouses/warehouse-form.component').then(c => c.WarehouseFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Warehouses.Create' },
  },
  {
    path: 'inventory/warehouses/:id/edit',
    loadComponent: () => import('./inventory/warehouses/warehouse-form.component').then(c => c.WarehouseFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Warehouses.Edit' },
  },
  {
    path: 'inventory/stock-entries/new',
    loadComponent: () => import('./inventory/stock-entries/stock-entry-form.component').then(c => c.StockEntryFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.StockEntries.Create' },
  },
  {
    path: 'inventory/stock-entries',
    loadComponent: () => import('./inventory/stock-entries/stock-entry-list.component').then(c => c.StockEntryListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.StockEntries' },
  },
  {
    path: 'inventory/stock-entries/:id',
    loadComponent: () => import('./inventory/stock-entries/stock-entry-detail.component').then(c => c.StockEntryDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.StockEntries' },
  },
  {
    path: 'inventory/quality-inspections',
    loadComponent: () => import('./inventory/quality-inspections/quality-inspection-list.component').then(c => c.QualityInspectionListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.QualityInspections' },
  },
  {
    path: 'inventory/stock-reconciliations',
    loadComponent: () => import('./inventory/stock-reconciliations/stock-reconciliation-list.component').then(c => c.StockReconciliationListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.StockReconciliations' },
  },
  {
    path: 'inventory/landed-costs',
    loadComponent: () => import('./inventory/landed-costs/landed-cost-list.component').then(c => c.LandedCostListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.LandedCostVouchers' },
  },
  {
    path: 'inventory/stock-reservations',
    loadComponent: () => import('./inventory/stock-reservations/stock-reservation-list.component').then(c => c.StockReservationListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.StockEntries' },
  },
  {
    path: 'inventory/item-attributes',
    loadComponent: () => import('./inventory/item-attributes/item-attribute-list.component').then(c => c.ItemAttributeListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Items' },
  },
  {
    path: 'inventory/reports/stock-ledger',
    loadComponent: () => import('./inventory/reports/stock-ledger/stock-ledger.component').then(c => c.StockLedgerComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Items' },
  },
  {
    path: 'inventory/reports/stock-balance',
    loadComponent: () => import('./inventory/reports/stock-balance.component').then(c => c.StockBalanceComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Items' },
  },
  {
    path: 'inventory/items/new',
    loadComponent: () => import('./inventory/items/item-form.component').then(c => c.ItemFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Items.Create' },
  },
  {
    path: 'inventory/items/:id/edit',
    loadComponent: () => import('./inventory/items/item-form.component').then(c => c.ItemFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Items.Edit' },
  },
  {
    path: 'e-invoice/logs',
    loadComponent: () => import('./e-invoice/logs/einvoice-logs.component').then(c => c.EinvoiceLogsComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.EInvoice' },
  },
  {
    path: 'sales/delivery-notes',
    loadComponent: () => import('./sales/delivery-notes/delivery-note-list.component').then(c => c.DeliveryNoteListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.DeliveryNotes' },
  },
  {
    path: 'sales/delivery-notes/new',
    loadComponent: () => import('./sales/delivery-notes/delivery-note-form.component').then(c => c.DeliveryNoteFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.DeliveryNotes.Create' },
  },
  {
    path: 'sales/delivery-notes/:id',
    loadComponent: () => import('./sales/delivery-notes/delivery-note-detail.component').then(c => c.DeliveryNoteDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.DeliveryNotes' },
  },
  {
    path: 'sales/pos',
    loadComponent: () => import('./sales/pos/pos.component').then(c => c.PosComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.POS' },
  },
  {
    path: 'purchasing/receipts',
    loadComponent: () => import('./purchasing/purchase-receipts/purchase-receipt-list.component').then(c => c.PurchaseReceiptListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseReceipts' },
  },
  {
    path: 'purchasing/receipts/new',
    loadComponent: () => import('./purchasing/purchase-receipts/purchase-receipt-form.component').then(c => c.PurchaseReceiptFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.PurchaseReceipts' },
  },
  {
    path: 'purchasing/receipts/:id',
    loadComponent: () => import('./purchasing/purchase-receipts/purchase-receipt-detail.component').then(c => c.PurchaseReceiptDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseReceipts' },
  },
  {
    path: 'accounting/bank-reconciliation',
    loadComponent: () => import('./accounting/bank-reconciliation/bank-reconciliation.component').then(c => c.BankReconciliationComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.BankReconciliation' },
  },
  {
    path: 'accounting/payment-reconciliation',
    loadComponent: () => import('./accounting/payment-reconciliation/payment-reconciliation.component').then(c => c.PaymentReconciliationComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PaymentEntries' },
  },
  {
    path: 'accounting/bank-statement-import',
    loadComponent: () => import('./accounting/bank-statement-import/bank-statement-import.component').then(c => c.BankStatementImportComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PaymentEntries' },
  },
  {
    path: 'e-invoice/reports',
    loadComponent: () => import('./e-invoice/reports/einvoice-status-report.component').then(c => c.EinvoiceStatusReportComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.EInvoice' },
  },
  {
    path: 'workflow/pending',
    loadComponent: () => import('./workflow/pending-approvals/pending-approvals.component').then(c => c.PendingApprovalsComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.ApprovalWorkflows' },
  },
  {
    path: 'workflow/rules',
    loadComponent: () => import('./workflow/approval-rules/approval-rules-list.component').then(c => c.ApprovalRulesListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.ApprovalWorkflows' },
  },
  {
    path: 'workflow/rules/new',
    loadComponent: () => import('./workflow/approval-rules/approval-rule-form.component').then(c => c.ApprovalRuleFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.ApprovalWorkflows' },
  },
  {
    path: 'import-export',
    loadComponent: () => import('./import-export/import-export.component').then(c => c.ImportExportComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.ImportExport' },
  },
  {
    path: 'automation',
    loadComponent: () => import('./automation/automation-rules/automation-rule-list.component').then(c => c.AutomationRuleListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.AutomationRules' },
  },
  {
    path: 'automation/new',
    loadComponent: () => import('./automation/automation-rules/automation-rule-form.component').then(c => c.AutomationRuleFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.AutomationRules.Create' },
  },
  {
    path: 'hr/employees',
    loadComponent: () => import('./hr/employees/employee-list.component').then(c => c.EmployeeListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Employees' },
  },
  {
    path: 'hr/employees/new',
    loadComponent: () => import('./hr/employees/employee-form.component').then(c => c.EmployeeFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Employees.Create' },
  },
  {
    path: 'hr/employees/:id/edit',
    loadComponent: () => import('./hr/employees/employee-form.component').then(c => c.EmployeeFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Employees.Edit' },
  },
  {
    path: 'hr/payroll',
    loadComponent: () => import('./hr/payroll/payroll-list.component').then(c => c.PayrollListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Employees' },
  },
  {
    path: 'hr/payroll/:id',
    loadComponent: () => import('./hr/payroll/payroll-detail.component').then(c => c.PayrollDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Employees' },
  },
  {
    path: 'tax/categories',
    loadComponent: () => import('./tax/tax-categories/tax-categories.component').then(c => c.TaxCategoriesComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.TaxCategories' },
  },
  {
    path: 'tax/summary',
    loadComponent: () => import('./tax/tax-summary-report/tax-summary-report.component').then(c => c.TaxSummaryReportComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.TaxCategories' },
  },
  {
    path: 'tax/sst02-filing',
    loadComponent: () => import('./tax/sst02-filing/sst02-filing.component').then(c => c.Sst02FilingComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.TaxCategories' },
  },
  // CRM
  {
    path: 'crm/leads',
    loadComponent: () => import('./crm/leads/lead-list.component').then(c => c.LeadListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Leads' },
  },
  {
    path: 'crm/leads/new',
    loadComponent: () => import('./crm/leads/lead-form.component').then(c => c.LeadFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Leads.Create' },
  },
  {
    path: 'crm/leads/:id/edit',
    loadComponent: () => import('./crm/leads/lead-form.component').then(c => c.LeadFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Leads.Edit' },
  },
  {
    path: 'crm/leads/:id',
    loadComponent: () => import('./crm/leads/lead-detail.component').then(c => c.LeadDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Leads' },
  },
  {
    path: 'crm/opportunities',
    loadComponent: () => import('./crm/opportunities/opportunity-list.component').then(c => c.OpportunityListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Opportunities' },
  },
  {
    path: 'crm/opportunities/new',
    loadComponent: () => import('./crm/opportunities/opportunity-form.component').then(c => c.OpportunityFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Opportunities.Create' },
  },
  {
    path: 'crm/opportunities/:id',
    loadComponent: () => import('./crm/opportunities/opportunity-detail.component').then(c => c.OpportunityDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Opportunities' },
  },
  {
    path: 'crm/opportunities/:id/edit',
    loadComponent: () => import('./crm/opportunities/opportunity-form.component').then(c => c.OpportunityFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Opportunities.Edit' },
  },
  // Projects
  {
    path: 'projects',
    loadComponent: () => import('./projects/project-list/project-list.component').then(c => c.ProjectListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Projects' },
  },
  {
    path: 'projects/new',
    loadComponent: () => import('./projects/project-form/project-form.component').then(c => c.ProjectFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Projects.Create' },
  },
  // Timesheets (must be before projects/:id to avoid param capture)
  {
    path: 'projects/timesheets',
    loadComponent: () => import('./projects/timesheets/timesheet-list.component').then(c => c.TimesheetListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Projects' },
  },
  {
    path: 'projects/timesheets/new',
    loadComponent: () => import('./projects/timesheets/timesheet-form.component').then(c => c.TimesheetFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Projects.Create' },
  },
  {
    path: 'projects/timesheets/:id',
    loadComponent: () => import('./projects/timesheets/timesheet-detail.component').then(c => c.TimesheetDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Projects' },
  },
  {
    path: 'projects/timesheet-billing',
    loadComponent: () => import('./projects/timesheet-billing/timesheet-billing.component').then(c => c.TimesheetBillingComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Projects' },
  },
  {
    path: 'projects/:id',
    loadComponent: () => import('./projects/project-form/project-form.component').then(c => c.ProjectFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Projects' },
  },
  {
    path: 'projects/:id/edit',
    loadComponent: () => import('./projects/project-form/project-form.component').then(c => c.ProjectFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Projects.Edit' },
  },
  // Assets
  {
    path: 'assets',
    loadComponent: () => import('./assets/asset-list/asset-list.component').then(c => c.AssetListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Assets' },
  },
  {
    path: 'assets/new',
    loadComponent: () => import('./assets/asset-form/asset-form.component').then(c => c.AssetFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Assets.Create' },
  },
  {
    path: 'assets/:id',
    loadComponent: () => import('./assets/asset-form/asset-form.component').then(c => c.AssetFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Assets' },
  },
  {
    path: 'assets/repairs',
    loadComponent: () => import('./assets/repairs/asset-repair-list.component').then(c => c.AssetRepairListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Assets' },
  },
  // Manufacturing
  {
    path: 'manufacturing/bom',
    loadComponent: () => import('./manufacturing/bom/bom-list.component').then(c => c.BomListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Manufacturing' },
  },
  {
    path: 'manufacturing/bom/new',
    loadComponent: () => import('./manufacturing/bom/bom-form.component').then(c => c.BomFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Manufacturing' },
  },
  {
    path: 'manufacturing/bom/:id',
    loadComponent: () => import('./manufacturing/bom/bom-form.component').then(c => c.BomFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Manufacturing' },
  },
  {
    path: 'manufacturing/work-orders',
    loadComponent: () => import('./manufacturing/work-orders/work-order-list.component').then(c => c.WorkOrderListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Manufacturing' },
  },
  {
    path: 'manufacturing/work-orders/new',
    loadComponent: () => import('./manufacturing/work-orders/work-order-form.component').then(c => c.WorkOrderFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Manufacturing.Create' },
  },
  {
    path: 'manufacturing/work-orders/:id',
    loadComponent: () => import('./manufacturing/work-orders/work-order-detail.component').then(c => c.WorkOrderDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Manufacturing' },
  },
  // Production Plans
  {
    path: 'manufacturing/production-plans',
    loadComponent: () => import('./manufacturing/production-plans/production-plan-list.component').then(c => c.ProductionPlanListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.ProductionPlans' },
  },
  {
    path: 'manufacturing/production-plans/new',
    loadComponent: () => import('./manufacturing/production-plans/production-plan-form.component').then(c => c.ProductionPlanFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.ProductionPlans.Create' },
  },
  {
    path: 'manufacturing/production-plans/:id',
    loadComponent: () => import('./manufacturing/production-plans/production-plan-detail.component').then(c => c.ProductionPlanDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.ProductionPlans' },
  },
  // Material Requests
  {
    path: 'purchasing/material-requests',
    loadComponent: () => import('./purchasing/material-requests/material-request-list.component').then(c => c.MaterialRequestListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.MaterialRequests' },
  },
  {
    path: 'purchasing/material-requests/new',
    loadComponent: () => import('./purchasing/material-requests/material-request-form.component').then(c => c.MaterialRequestFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.MaterialRequests.Create' },
  },
  {
    path: 'purchasing/material-requests/:id',
    loadComponent: () => import('./purchasing/material-requests/material-request-detail.component').then(c => c.MaterialRequestDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.MaterialRequests' },
  },
  // Support
  {
    path: 'support/issues',
    loadComponent: () => import('./support/issues/issue-list.component').then(c => c.IssueListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Issues' },
  },
  {
    path: 'support/issues/new',
    loadComponent: () => import('./support/issues/issue-form.component').then(c => c.IssueFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Issues.Create' },
  },
  // Leave
  {
    path: 'hr/leave',
    loadComponent: () => import('./hr/leave/leave-list.component').then(c => c.LeaveListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Employees' },
  },
  {
    path: 'hr/leave/apply',
    loadComponent: () => import('./hr/leave/leave-form.component').then(c => c.LeaveFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Employees.Create' },
  },
  {
    path: 'hr/salary-slips',
    loadComponent: () => import('./hr/salary-slips/salary-slip-list.component').then(c => c.SalarySlipListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Payroll' },
  },
  {
    path: 'hr/salary-slips/:id',
    loadComponent: () => import('./hr/salary-slips/salary-slip-detail.component').then(c => c.SalarySlipDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Payroll' },
  },
  {
    path: 'hr/holiday-lists',
    loadComponent: () => import('./hr/holiday-lists/holiday-list-list.component').then(c => c.HolidayListListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Employees' },
  },
  {
    path: 'hr/salary-structures',
    loadComponent: () => import('./hr/salary-structures/salary-structure-list.component').then(c => c.SalaryStructureListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Payroll' },
  },
  {
    path: 'hr/leave-allocations',
    loadComponent: () => import('./hr/leave-allocation/leave-allocation-list.component').then(c => c.LeaveAllocationListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Employees.Edit' },
  },
  {
    path: 'manufacturing/workstations',
    loadComponent: () => import('./manufacturing/workstations/workstation-list.component').then(c => c.WorkstationListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Manufacturing' },
  },
  {
    path: 'manufacturing/job-cards',
    loadComponent: () => import('./manufacturing/job-cards/job-card-list.component').then(c => c.JobCardListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Manufacturing' },
  },
  {
    path: 'sales/blanket-orders',
    loadComponent: () => import('./sales/blanket-orders/blanket-order-list.component').then(c => c.BlanketOrderListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesOrders' },
  },
  {
    path: 'sales/subscriptions',
    loadComponent: () => import('./sales/subscriptions/subscription-list.component').then(c => c.SubscriptionListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'sales/pricing-rules',
    loadComponent: () => import('./sales/pricing-rules/pricing-rule-list.component').then(c => c.PricingRuleListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'purchasing/supplier-quotations',
    loadComponent: () => import('./purchasing/supplier-quotations/supplier-quotation-list.component').then(c => c.SupplierQuotationListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseOrders' },
  },
  {
    path: 'purchasing/subcontracting',
    loadComponent: () => import('./purchasing/subcontracting/subcontracting-list.component').then(c => c.SubcontractingListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseOrders' },
  },
  {
    path: 'purchasing/rfq',
    loadComponent: () => import('./purchasing/rfq/rfq-list.component').then(c => c.RfqListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseOrders' },
  },
  {
    path: 'purchasing/rfq/new',
    loadComponent: () => import('./purchasing/rfq/rfq-form.component').then(c => c.RfqFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.PurchaseOrders.Create' },
  },
  {
    path: 'sales/pos-closing',
    loadComponent: () => import('./sales/pos-closing/pos-closing-list.component').then(c => c.PosClosingListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'sales/loyalty-programs',
    loadComponent: () => import('./sales/loyalty-programs/loyalty-program-list.component').then(c => c.LoyaltyProgramListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.LoyaltyPrograms' },
  },
  {
    path: 'sales/shipping-rules',
    loadComponent: () => import('./sales/shipping-rules/shipping-rule-list.component').then(c => c.ShippingRuleListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.ShippingRules' },
  },
  {
    path: 'sales/sales-persons',
    loadComponent: () => import('./sales/sales-persons/sales-person-list.component').then(c => c.SalesPersonListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesPersons' },
  },
  {
    path: 'purchasing/scorecards',
    loadComponent: () => import('./purchasing/scorecards/supplier-scorecard-list.component').then(c => c.SupplierScorecardListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SupplierScorecards' },
  },
  {
    path: 'sales/loyalty-programs/new',
    loadComponent: () => import('./sales/loyalty-programs/loyalty-program-form.component').then(c => c.LoyaltyProgramFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave?')],
    data: { requiredPolicy: 'MyERP.LoyaltyPrograms.Create' },
  },
  {
    path: 'sales/shipping-rules/new',
    loadComponent: () => import('./sales/shipping-rules/shipping-rule-form.component').then(c => c.ShippingRuleFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave?')],
    data: { requiredPolicy: 'MyERP.ShippingRules.Create' },
  },
  {
    path: 'sales/sales-persons/new',
    loadComponent: () => import('./sales/sales-persons/sales-person-form.component').then(c => c.SalesPersonFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave?')],
    data: { requiredPolicy: 'MyERP.SalesPersons.Create' },
  },
  {
    path: 'purchasing/scorecards/new',
    loadComponent: () => import('./purchasing/scorecards/supplier-scorecard-form.component').then(c => c.SupplierScorecardFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave?')],
    data: { requiredPolicy: 'MyERP.SupplierScorecards.Create' },
  },
  {
    path: 'hr/expense-claims',
    loadComponent: () => import('./hr/expense-claims/expense-claim-list.component').then(c => c.ExpenseClaimListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Employees' },
  },
  {
    path: 'sales/dunnings',
    loadComponent: () => import('./sales/dunnings/dunning-list.component').then(c => c.DunningListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'inventory/serial-numbers',
    loadComponent: () => import('./inventory/serial-numbers/serial-no-list.component').then(c => c.SerialNoListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Items' },
  },
  {
    path: 'inventory/batches',
    loadComponent: () => import('./inventory/batches/batch-list.component').then(c => c.BatchListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Items' },
  },
  {
    path: 'hr/expense-claims/new',
    loadComponent: () => import('./hr/expense-claims/expense-claim-form.component').then(c => c.ExpenseClaimFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Employees.Create' },
  },
  {
    path: 'sales/blanket-orders/new',
    loadComponent: () => import('./sales/blanket-orders/blanket-order-form.component').then(c => c.BlanketOrderFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.SalesOrders.Create' },
  },
  {
    path: 'purchasing/supplier-quotations/new',
    loadComponent: () => import('./purchasing/supplier-quotations/supplier-quotation-form.component').then(c => c.SupplierQuotationFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.PurchaseOrders.Create' },
  },

  // Detail routes for gap-fill entities
  {
    path: 'sales/loyalty-programs/:id',
    loadComponent: () => import('./sales/loyalty-programs/loyalty-program-detail.component').then(c => c.LoyaltyProgramDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.LoyaltyPrograms' },
  },
  {
    path: 'sales/shipping-rules/:id',
    loadComponent: () => import('./sales/shipping-rules/shipping-rule-detail.component').then(c => c.ShippingRuleDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.ShippingRules' },
  },
  {
    path: 'sales/sales-persons/:id',
    loadComponent: () => import('./sales/sales-persons/sales-person-detail.component').then(c => c.SalesPersonDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesPersons' },
  },
  {
    path: 'sales/pricing-rules/:id',
    loadComponent: () => import('./sales/pricing-rules/pricing-rule-detail.component').then(c => c.PricingRuleDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'sales/blanket-orders/:id',
    loadComponent: () => import('./sales/blanket-orders/blanket-order-detail.component').then(c => c.BlanketOrderDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesOrders' },
  },
  {
    path: 'purchasing/scorecards/:id',
    loadComponent: () => import('./purchasing/scorecards/supplier-scorecard-detail.component').then(c => c.SupplierScorecardDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SupplierScorecards' },
  },
  {
    path: 'purchasing/rfq/:id',
    loadComponent: () => import('./purchasing/rfq/rfq-detail.component').then(c => c.RfqDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseOrders' },
  },
  {
    path: 'purchasing/supplier-quotations/:id',
    loadComponent: () => import('./purchasing/supplier-quotations/supplier-quotation-detail.component').then(c => c.SupplierQuotationDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PurchaseOrders' },
  },
  {
    path: 'manufacturing/workstations/:id',
    loadComponent: () => import('./manufacturing/workstations/workstation-detail.component').then(c => c.WorkstationDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Manufacturing' },
  },

  // New/create routes for recently added modules (MUST be before :id routes — Gotcha #50)
  {
    path: 'accounting/budgets/new',
    loadComponent: () => import('./accounting/budgets/budget-form.component').then(c => c.BudgetFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Budgets.Create' },
  },
  {
    path: 'hr/holiday-lists/new',
    loadComponent: () => import('./hr/holiday-lists/holiday-list-form.component').then(c => c.HolidayListFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Employees.Create' },
  },
  {
    path: 'hr/salary-structures/new',
    loadComponent: () => import('./hr/salary-structures/salary-structure-form.component').then(c => c.SalaryStructureFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Payroll.Create' },
  },
  {
    path: 'inventory/landed-costs/new',
    loadComponent: () => import('./inventory/landed-costs/landed-cost-form.component').then(c => c.LandedCostFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.LandedCostVouchers.Create' },
  },
  {
    path: 'inventory/quality-inspections/new',
    loadComponent: () => import('./inventory/quality-inspections/quality-inspection-form.component').then(c => c.QualityInspectionFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.QualityInspections.Create' },
  },
  {
    path: 'inventory/stock-reconciliations/new',
    loadComponent: () => import('./inventory/stock-reconciliations/stock-reconciliation-form.component').then(c => c.StockReconciliationFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.StockReconciliations.Create' },
  },
  {
    path: 'manufacturing/workstations/new',
    loadComponent: () => import('./manufacturing/workstations/workstation-form.component').then(c => c.WorkstationFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.Manufacturing.Create' },
  },

  // Detail routes for recently added modules
  {
    path: 'accounting/budgets/:id',
    loadComponent: () => import('./accounting/budgets/budget-detail.component').then(c => c.BudgetDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Budgets' },
  },
  {
    path: 'hr/expense-claims/:id',
    loadComponent: () => import('./hr/expense-claims/expense-claim-detail.component').then(c => c.ExpenseClaimDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Employees' },
  },
  {
    path: 'hr/holiday-lists/:id',
    loadComponent: () => import('./hr/holiday-lists/holiday-list-detail.component').then(c => c.HolidayListDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Employees' },
  },
  {
    path: 'inventory/landed-costs/:id',
    loadComponent: () => import('./inventory/landed-costs/landed-cost-detail.component').then(c => c.LandedCostDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.LandedCostVouchers' },
  },
  {
    path: 'inventory/quality-inspections/:id',
    loadComponent: () => import('./inventory/quality-inspections/quality-inspection-detail.component').then(c => c.QualityInspectionDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.QualityInspections' },
  },
  {
    path: 'inventory/stock-reconciliations/:id',
    loadComponent: () => import('./inventory/stock-reconciliations/stock-reconciliation-detail.component').then(c => c.StockReconciliationDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.StockReconciliations' },
  },
  {
    path: 'support/issues/:id',
    loadComponent: () => import('./support/issues/issue-detail.component').then(c => c.IssueDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Issues' },
  },

  // Edit routes (reuse form components)
  {
    path: 'accounting/journal-entries/:id',
    loadComponent: () => import('./accounting/journal-entries/journal-entry-detail.component').then(c => c.JournalEntryDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.JournalEntries' },
  },
  {
    path: 'automation/:id/edit',
    loadComponent: () => import('./automation/automation-rules/automation-rule-form.component').then(c => c.AutomationRuleFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.AutomationRules.Edit' },
  },
  {
    path: 'purchasing/orders/:id/edit',
    loadComponent: () => import('./purchasing/purchase-orders/purchase-order-form.component').then(c => c.PurchaseOrderFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.PurchaseOrders.Edit' },
  },
  {
    path: 'workflow/rules/:id/edit',
    loadComponent: () => import('./workflow/approval-rules/approval-rule-form.component').then(c => c.ApprovalRuleFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.ApprovalWorkflows.Edit' },
  },

  {
    path: 'sales/pricing-rules/new',
    loadComponent: () => import('./sales/pricing-rules/pricing-rule-form.component').then(c => c.PricingRuleFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.SalesInvoices.Create' },
  },
  {
    path: 'sales/subscriptions/new',
    loadComponent: () => import('./sales/subscriptions/subscription-form.component').then(c => c.SubscriptionFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.SalesInvoices.Create' },
  },

  // Detail views for newer modules
  {
    path: 'manufacturing/job-cards/:id',
    loadComponent: () => import('./manufacturing/job-cards/job-card-detail.component').then(c => c.JobCardDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Manufacturing' },
  },
  {
    path: 'sales/subscriptions/:id',
    loadComponent: () => import('./sales/subscriptions/subscription-detail.component').then(c => c.SubscriptionDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'sales/dunnings/:id',
    loadComponent: () => import('./sales/dunnings/dunning-detail.component').then(c => c.DunningDetailComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.SalesInvoices' },
  },
  {
    path: 'hr/salary-structures/:id',
    loadComponent: () => import('./hr/salary-structures/salary-structure-form.component').then(c => c.SalaryStructureFormComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Payroll' },
  },
  {
    path: 'sales/dunnings/new',
    loadComponent: () => import('./sales/dunnings/dunning-form.component').then(c => c.DunningFormComponent),
    canActivate: [authGuard, permissionGuard],
    canDeactivate: [(c: any) => !c?.hasUnsavedChanges?.() || confirm('You have unsaved changes. Leave page?')],
    data: { requiredPolicy: 'MyERP.SalesInvoices.Create' },
  },
  {
    path: 'accounting/currency-exchange',
    loadComponent: () => import('./accounting/currency-exchange/currency-exchange.component').then(c => c.CurrencyExchangeComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'accounting/fiscal-years',
    loadComponent: () => import('./accounting/fiscal-years/fiscal-year-list.component').then(c => c.FiscalYearListComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'accounting/period-closing',
    loadComponent: () => import('./accounting/period-closing/period-closing.component').then(c => c.PeriodClosingComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'accounting/opening-balance',
    loadComponent: () => import('./accounting/opening-balance/opening-balance.component').then(c => c.OpeningBalanceComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.JournalEntries.Create' },
  },
  {
    path: 'accounting/dimensions',
    loadComponent: () => import('./accounting/dimensions/accounting-dimensions.component').then(c => c.AccountingDimensionsComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'accounting/batch-payment',
    loadComponent: () => import('./accounting/batch-payment/batch-payment.component').then(c => c.BatchPaymentComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.PaymentEntries.Create' },
  },
  {
    path: 'accounting/reports/cash-flow',
    loadComponent: () => import('./accounting/reports/cash-flow/cash-flow-statement.component').then(c => c.CashFlowStatementComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: 'accounting/reports/budget-variance',
    loadComponent: () => import('./accounting/reports/budget-variance/budget-variance-report.component').then(c => c.BudgetVarianceReportComponent),
    canActivate: [authGuard, permissionGuard],
    data: { requiredPolicy: 'MyERP.Accounts' },
  },
  {
    path: '**',
    loadComponent: () => import('./shared/components/not-found/not-found.component').then(c => c.NotFoundComponent),
  },
];
