import { RoutesService, eLayoutType } from '@abp/ng.core';
import { inject, provideAppInitializer } from '@angular/core';
export const APP_ROUTE_PROVIDER = [
  provideAppInitializer(() => {
    configureRoutes();
  }),
];
function configureRoutes() {
  const routes = inject(RoutesService);
  routes.add([
      {
        path: '/',
        name: '::Menu:Home',
        iconClass: 'fas fa-home',
        order: 1,
        layout: eLayoutType.application,
      },
      {
        path: '/companies',
        name: '::Menu:Companies',
        iconClass: 'fas fa-building',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Companies',
      },
      {
        path: '/customers',
        name: '::Menu:Customers',
        iconClass: 'fas fa-users',
        order: 3,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Customers',
      },
      {
        path: '/invoices',
        name: 'Sales Invoices',
        iconClass: 'fas fa-file-invoice',
        order: 4,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesInvoices',
      },
      {
        path: '/sales',
        name: '::Menu:Sales',
        iconClass: 'fas fa-shopping-cart',
        order: 10,
        layout: eLayoutType.application,
      },
      {
        path: '/sales/quotations',
        name: '::Menu:Quotations',
        parentName: '::Menu:Sales',
        iconClass: 'fas fa-file-lines',
        order: 1,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Quotations',
      },
      {
        path: '/sales/orders',
        name: '::Menu:SalesOrders',
        parentName: '::Menu:Sales',
        iconClass: 'fas fa-clipboard-list',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesOrders',
      },
      {
        path: '/sales/invoices',
        name: '::Menu:SalesInvoices',
        parentName: '::Menu:Sales',
        iconClass: 'fas fa-file-invoice-dollar',
        order: 3,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesInvoices',
      },
      {
        path: '/sales/delivery-notes',
        name: '::Menu:DeliveryNotes',
        parentName: '::Menu:Sales',
        iconClass: 'fas fa-truck-fast',
        order: 4,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.DeliveryNotes',
      },
      {
        path: '/sales/pos',
        name: '::Menu:POS',
        parentName: '::Menu:Sales',
        iconClass: 'fas fa-cash-register',
        order: 10,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.POS',
      },
      {
        path: '/suppliers',
        name: '::Menu:Suppliers',
        iconClass: 'fas fa-truck',
        order: 5,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Suppliers',
      },
      {
        path: '/e-invoice',
        name: '::Menu:EInvoice',
        iconClass: 'fas fa-file-signature',
        order: 20,
        layout: eLayoutType.application,
      },
      {
        path: '/e-invoice/dashboard',
        name: '::Menu:LhdnDashboard',
        parentName: '::Menu:EInvoice',
        iconClass: 'fas fa-chart-pie',
        order: 1,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.EInvoice',
      },
      {
        path: '/e-invoice/logs',
        name: '::Menu:SubmissionLogs',
        parentName: '::Menu:EInvoice',
        iconClass: 'fas fa-list-check',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.EInvoice',
      },
      {
        path: '/e-invoice/reports',
        name: '::Menu:EInvoiceStatusReport',
        parentName: '::Menu:EInvoice',
        iconClass: 'fas fa-table-list',
        order: 3,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.EInvoice',
      },
      {
        path: '/purchasing',
        name: '::Menu:Purchasing',
        iconClass: 'fas fa-cart-shopping',
        order: 15,
        layout: eLayoutType.application,
      },
      {
        path: '/purchasing/orders',
        name: '::Menu:PurchaseOrders',
        parentName: '::Menu:Purchasing',
        iconClass: 'fas fa-clipboard-list',
        order: 1,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.PurchaseOrders',
      },
      {
        path: '/purchasing/invoices',
        name: '::Menu:PurchaseInvoices',
        parentName: '::Menu:Purchasing',
        iconClass: 'fas fa-file-invoice',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.PurchaseInvoices',
      },
      {
        path: '/purchasing/receipts',
        name: '::Menu:PurchaseReceipts',
        parentName: '::Menu:Purchasing',
        iconClass: 'fas fa-box-open',
        order: 3,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.PurchaseReceipts',
      },
      {
        path: '/accounting',
        name: '::Menu:Accounting',
        iconClass: 'fas fa-calculator',
        order: 30,
        layout: eLayoutType.application,
      },
      {
        path: '/accounting/accounts',
        name: '::Menu:ChartOfAccounts',
        parentName: '::Menu:Accounting',
        iconClass: 'fas fa-sitemap',
        order: 1,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/journal-entries/new',
        name: '::Menu:JournalEntry',
        parentName: '::Menu:Accounting',
        iconClass: 'fas fa-book',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.JournalEntries.Create',
      },
      {
        path: '/accounting/payments/new',
        name: '::Menu:PaymentEntry',
        parentName: '::Menu:Accounting',
        iconClass: 'fas fa-money-bill-transfer',
        order: 3,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.PaymentEntries.Create',
      },
      {
        path: '/accounting/reports/trial-balance',
        name: '::Menu:TrialBalance',
        parentName: '::Menu:Accounting',
        iconClass: 'fas fa-balance-scale',
        order: 10,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/reports/profit-loss',
        name: '::Menu:ProfitLoss',
        parentName: '::Menu:Accounting',
        iconClass: 'fas fa-chart-line',
        order: 11,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/reports/balance-sheet',
        name: '::Menu:BalanceSheet',
        parentName: '::Menu:Accounting',
        iconClass: 'fas fa-scale-balanced',
        order: 12,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/bank-reconciliation',
        name: '::Menu:BankReconciliation',
        parentName: '::Menu:Accounting',
        iconClass: 'fas fa-building-columns',
        order: 20,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.BankReconciliation',
      },
      {
        path: '/inventory',
        name: '::Menu:Inventory',
        iconClass: 'fas fa-warehouse',
        order: 35,
        layout: eLayoutType.application,
      },
      {
        path: '/inventory/items',
        name: '::Menu:Items',
        parentName: '::Menu:Inventory',
        iconClass: 'fas fa-box',
        order: 1,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Items',
      },
      {
        path: '/inventory/warehouses',
        name: '::Menu:Warehouses',
        parentName: '::Menu:Inventory',
        iconClass: 'fas fa-building-columns',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Warehouses',
      },
      {
        path: '/inventory/stock-entries',
        name: '::Menu:StockEntries',
        parentName: '::Menu:Inventory',
        iconClass: 'fas fa-right-left',
        order: 3,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.StockEntries',
      },
      {
        path: '/inventory/reports/stock-ledger',
        name: '::Menu:StockLedger',
        parentName: '::Menu:Inventory',
        iconClass: 'fas fa-scroll',
        order: 10,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.StockLedger',
      },
      {
        path: '/workflow',
        name: '::Menu:Workflow',
        iconClass: 'fas fa-list-check',
        order: 40,
        layout: eLayoutType.application,
      },
      {
        path: '/workflow/pending',
        name: '::Menu:PendingApprovals',
        parentName: '::Menu:Workflow',
        iconClass: 'fas fa-clock',
        order: 1,
        layout: eLayoutType.application,
      },
      {
        path: '/workflow/rules',
        name: '::Menu:ApprovalRules',
        parentName: '::Menu:Workflow',
        iconClass: 'fas fa-gears',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.ApprovalWorkflows',
      },
      {
        path: '/import-export',
        name: '::Menu:ImportExport',
        iconClass: 'fas fa-file-import',
        order: 50,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.ImportExport',
      },
      {
        path: '/automation',
        name: '::Menu:Automation',
        iconClass: 'fas fa-robot',
        order: 45,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.AutomationRules',
      },
      {
        path: '/hr',
        name: '::Menu:HR',
        iconClass: 'fas fa-users',
        order: 50,
        layout: eLayoutType.application,
      },
      {
        path: '/hr/employees',
        name: '::Menu:Employees',
        parentName: '::Menu:HR',
        iconClass: 'fas fa-user-tie',
        order: 1,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Employees',
      },
      {
        path: '/hr/payroll',
        name: '::Menu:Payroll',
        parentName: '::Menu:HR',
        iconClass: 'fas fa-money-check-alt',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Employees',
      },
      {
        path: '/tax/categories',
        name: '::Menu:TaxCategories',
        iconClass: 'fas fa-percent',
        order: 55,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.TaxCategories',
      },
  ]);
}
