import { RoutesService, eLayoutType } from '@abp/ng.core';
import { inject, provideAppInitializer } from '@angular/core';
export const APP_ROUTE_PROVIDER = [
  provideAppInitializer(() => {
    configureRoutes();
  })];
function configureRoutes() {
  const routes = inject(RoutesService);
  routes.add([
      {
        path: '/',
        name: '::Menu:Home',
        iconClass: 'fas fa-home',
        order: 1,
        layout: eLayoutType.application,
      },
      {
        path: '/companies',
        name: '::Menu:Companies',
        iconClass: 'fas fa-building',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Companies',
      },
      {
        path: '/customers',
        name: '::Menu:Customers',
        iconClass: 'fas fa-users',
        order: 3,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Customers',
      },
      {
        path: '/sales',
        name: '::Menu:Sales',
        iconClass: 'fas fa-shopping-cart',
        order: 10,
        layout: eLayoutType.application,
      },
      {
        path: '/sales/quotations',
        name: '::Menu:Quotations',
        parentName: '::Menu:Sales',
        iconClass: 'fas fa-file-lines',
        order: 1,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Quotations',
      },
      {
        path: '/sales/orders',
        name: '::Menu:SalesOrders',
        parentName: '::Menu:Sales',
        iconClass: 'fas fa-clipboard-list',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesOrders',
      },
      {
        path: '/sales/invoices',
        name: '::Menu:SalesInvoices',
        parentName: '::Menu:Sales',
        iconClass: 'fas fa-file-invoice-dollar',
        order: 3,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesInvoices',
      },
      {
        path: '/sales/delivery-notes',
        name: '::Menu:DeliveryNotes',
        parentName: '::Menu:Sales',
        iconClass: 'fas fa-truck-fast',
        order: 4,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.DeliveryNotes',
      },
      {
        path: '/sales/pos',
        name: '::Menu:POS',
        parentName: '::Menu:Sales',
        iconClass: 'fas fa-cash-register',
        order: 10,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.POS',
      },
      {
        path: '/sales/pos-closing',
        name: '::Menu:POSClosing',
        parentName: '::Menu:Sales',
        iconClass: 'fas fa-register',
        order: 11,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesInvoices',
      },
      {
        path: '/sales/pos-opening',
        name: '::Menu:POSOpening',
        parentName: '::Menu:Sales',
        iconClass: 'fas fa-door-open',
        order: 12,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesInvoices',
      },
      {
        path: '/sales/loyalty-programs',
        name: '::Menu:LoyaltyPrograms',
        parentName: '::Menu:Sales',
        iconClass: 'fas fa-gift',
        order: 12,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.LoyaltyPrograms',
      },
      {
        path: '/sales/coupon-codes',
        name: '::Menu:CouponCodes',
        parentName: '::Menu:Sales',
        iconClass: 'fas fa-ticket',
        order: 13,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesInvoices',
      },
      {
        path: '/sales/packing-slips',
        name: '::Menu:PackingSlips',
        parentName: '::Menu:Sales',
        iconClass: 'fas fa-box',
        order: 14,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.DeliveryNotes',
      },
      {
        path: '/sales/shipping-rules',
        name: '::Menu:ShippingRules',
        parentName: '::Menu:Sales',
        iconClass: 'fas fa-truck-fast',
        order: 15,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.ShippingRules',
      },
      {
        path: '/sales/sales-persons',
        name: '::Menu:SalesPersons',
        parentName: '::Menu:Sales',
        iconClass: 'fas fa-user-tie',
        order: 14,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesPersons',
      },
      {
        path: '/suppliers',
        name: '::Menu:Suppliers',
        iconClass: 'fas fa-truck',
        order: 5,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Suppliers',
      },
      {
        path: '/e-invoice',
        name: '::Menu:EInvoice',
        iconClass: 'fas fa-file-signature',
        order: 20,
        layout: eLayoutType.application,
      },
      {
        path: '/e-invoice/dashboard',
        name: '::Menu:LhdnDashboard',
        parentName: '::Menu:EInvoice',
        iconClass: 'fas fa-chart-pie',
        order: 1,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.EInvoice',
      },
      {
        path: '/e-invoice/logs',
        name: '::Menu:SubmissionLogs',
        parentName: '::Menu:EInvoice',
        iconClass: 'fas fa-list-check',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.EInvoice',
      },
      {
        path: '/e-invoice/reports',
        name: '::Menu:EInvoiceStatusReport',
        parentName: '::Menu:EInvoice',
        iconClass: 'fas fa-table-list',
        order: 3,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.EInvoice',
      },
      {
        path: '/purchasing',
        name: '::Menu:Purchasing',
        iconClass: 'fas fa-cart-shopping',
        order: 15,
        layout: eLayoutType.application,
      },
      {
        path: '/purchasing/orders',
        name: '::Menu:PurchaseOrders',
        parentName: '::Menu:Purchasing',
        iconClass: 'fas fa-clipboard-list',
        order: 1,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.PurchaseOrders',
      },
      {
        path: '/purchasing/invoices',
        name: '::Menu:PurchaseInvoices',
        parentName: '::Menu:Purchasing',
        iconClass: 'fas fa-file-invoice',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.PurchaseInvoices',
      },
      {
        path: '/purchasing/receipts',
        name: '::Menu:PurchaseReceipts',
        parentName: '::Menu:Purchasing',
        iconClass: 'fas fa-box-open',
        order: 3,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.PurchaseReceipts',
      },
      {
        path: '/purchasing/material-requests',
        name: '::Menu:MaterialRequests',
        parentName: '::Menu:Purchasing',
        iconClass: 'fas fa-clipboard-list',
        order: 4,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.MaterialRequests',
      },
      {
        path: '/accounting',
        name: '::Menu:Accounting',
        iconClass: 'fas fa-calculator',
        order: 30,
        layout: eLayoutType.application,
      },
      {
        path: '/accounting/accounts',
        name: '::Menu:ChartOfAccounts',
        parentName: '::Menu:Accounting',
        iconClass: 'fas fa-sitemap',
        order: 1,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/journal-entries/new',
        name: '::Menu:JournalEntry',
        parentName: '::Menu:Accounting',
        iconClass: 'fas fa-book',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.JournalEntries.Create',
      },
      {
        path: '/accounting/payments/new',
        name: '::Menu:PaymentEntry',
        parentName: '::Menu:Accounting',
        iconClass: 'fas fa-money-bill-transfer',
        order: 3,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.PaymentEntries.Create',
      },
      {
        path: '/accounting/reports/trial-balance',
        name: '::Menu:TrialBalance',
        parentName: '::Menu:Accounting',
        iconClass: 'fas fa-balance-scale',
        order: 10,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/reports/profit-loss',
        name: '::Menu:ProfitLoss',
        parentName: '::Menu:Accounting',
        iconClass: 'fas fa-chart-line',
        order: 11,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/reports/balance-sheet',
        name: '::Menu:BalanceSheet',
        parentName: '::Menu:Accounting',
        iconClass: 'fas fa-scale-balanced',
        order: 12,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/bank-reconciliation',
        name: '::Menu:BankReconciliation',
        parentName: '::Menu:Accounting',
        iconClass: 'fas fa-building-columns',
        order: 20,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.BankReconciliation',
      },
      {
        path: '/accounting/bank-reconciliation-statement',
        name: '::Menu:BankReconciliationStatement',
        parentName: '::Menu:Accounting',
        iconClass: 'fas fa-file-lines',
        order: 21,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.PaymentEntries.Default',
      },
      {
        path: '/accounting/payment-reconciliation',
        name: '::Menu:PaymentReconciliation',
        parentName: '::Menu:Accounting',
        iconClass: 'fas fa-handshake',
        order: 21,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.PaymentEntries',
      },
      {
        path: '/accounting/budgets',
        name: '::Menu:Budgets',
        parentName: '::Menu:Accounting',
        iconClass: 'fas fa-calculator',
        order: 21,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Budgets',
      },
      {
        path: '/inventory',
        name: '::Menu:Inventory',
        iconClass: 'fas fa-warehouse',
        order: 35,
        layout: eLayoutType.application,
      },
      {
        path: '/inventory/items',
        name: '::Menu:Items',
        parentName: '::Menu:Inventory',
        iconClass: 'fas fa-box',
        order: 1,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Items',
      },
      {
        path: '/inventory/warehouses',
        name: '::Menu:Warehouses',
        parentName: '::Menu:Inventory',
        iconClass: 'fas fa-building-columns',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Warehouses',
      },
      {
        path: '/inventory/stock-entries',
        name: '::Menu:StockEntries',
        parentName: '::Menu:Inventory',
        iconClass: 'fas fa-right-left',
        order: 3,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.StockEntries',
      },
      {
        path: '/inventory/reports/stock-ledger',
        name: '::Menu:StockLedger',
        parentName: '::Menu:Inventory',
        iconClass: 'fas fa-scroll',
        order: 10,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.StockLedger',
      },
      {
        path: '/inventory/reports/stock-balance',
        name: '::Menu:StockBalance',
        parentName: '::Menu:Inventory',
        iconClass: 'fas fa-cubes',
        order: 11,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Items',
      },
      {
        path: '/inventory/quality-inspections',
        name: '::Menu:QualityInspections',
        parentName: '::Menu:Inventory',
        iconClass: 'fas fa-clipboard-check',
        order: 4,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.QualityInspections',
      },
      {
        path: '/inventory/stock-reconciliations',
        name: '::Menu:StockReconciliations',
        parentName: '::Menu:Inventory',
        iconClass: 'fas fa-scale-balanced',
        order: 5,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.StockReconciliations',
      },
      {
        path: '/inventory/landed-costs',
        name: '::Menu:LandedCostVouchers',
        parentName: '::Menu:Inventory',
        iconClass: 'fas fa-truck-ramp-box',
        order: 6,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.LandedCostVouchers',
      },
      {
        path: '/inventory/stock-reservations',
        name: '::Menu:StockReservations',
        parentName: '::Menu:Inventory',
        iconClass: 'fas fa-lock',
        order: 7,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.StockEntries',
      },
      {
        path: '/inventory/transit-transfers',
        name: '::Menu:TransitTransfers',
        parentName: '::Menu:Inventory',
        iconClass: 'fas fa-truck-moving',
        order: 8,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.StockEntries',
      },
      {
        path: '/inventory/standard-costs',
        name: '::Menu:ItemStandardCosts',
        parentName: '::Menu:Inventory',
        iconClass: 'fas fa-tag',
        order: 9,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.StockEntries',
      },
      {
        path: '/inventory/repost-valuation',
        name: '::Menu:RepostItemValuation',
        parentName: '::Menu:Inventory',
        iconClass: 'fas fa-rotate',
        order: 10,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.StockEntries',
      },
      {
        path: '/inventory/stock-closing',
        name: '::Menu:StockClosing',
        parentName: '::Menu:Inventory',
        iconClass: 'fas fa-box-archive',
        order: 11,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.StockEntries',
      },
      {
        path: '/inventory/item-attributes',
        name: '::Menu:ItemAttributes',
        parentName: '::Menu:Inventory',
        iconClass: 'fas fa-palette',
        order: 11,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Items',
      },
      {
        path: '/workflow',
        name: '::Menu:Workflow',
        iconClass: 'fas fa-list-check',
        order: 40,
        layout: eLayoutType.application,
      },
      {
        path: '/workflow/pending',
        name: '::Menu:PendingApprovals',
        parentName: '::Menu:Workflow',
        iconClass: 'fas fa-clock',
        order: 1,
        layout: eLayoutType.application,
      },
      {
        path: '/workflow/rules',
        name: '::Menu:ApprovalRules',
        parentName: '::Menu:Workflow',
        iconClass: 'fas fa-gears',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.ApprovalWorkflows',
      },
      {
        path: '/import-export',
        name: '::Menu:ImportExport',
        iconClass: 'fas fa-file-import',
        order: 50,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.ImportExport',
      },
      {
        path: '/automation',
        name: '::Menu:Automation',
        iconClass: 'fas fa-robot',
        order: 45,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.AutomationRules',
      },
      {
        path: '/hr',
        name: '::Menu:HR',
        iconClass: 'fas fa-users',
        order: 50,
        layout: eLayoutType.application,
      },
      {
        path: '/hr/employees',
        name: '::Menu:Employees',
        parentName: '::Menu:HR',
        iconClass: 'fas fa-user-tie',
        order: 1,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Employees',
      },
      {
        path: '/hr/payroll',
        name: '::Menu:Payroll',
        parentName: '::Menu:HR',
        iconClass: 'fas fa-money-check-alt',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Employees',
      },
      {
        path: '/tax/categories',
        name: '::Menu:TaxCategories',
        iconClass: 'fas fa-percent',
        order: 55,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.TaxCategories',
      },
      {
        path: '/tax/summary',
        name: '::Menu:TaxSummary',
        iconClass: 'fas fa-file-invoice-dollar',
        order: 56,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.TaxCategories',
      },
      {
        path: '/tax/sst02-filing',
        name: '::Menu:SST02Filing',
        iconClass: 'fas fa-file-circle-check',
        order: 57,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.TaxCategories',
      },
      {
        path: '/crm',
        name: '::Menu:CRM',
        iconClass: 'fas fa-handshake',
        order: 8,
        layout: eLayoutType.application,
      },
      {
        path: '/crm/leads',
        name: '::Menu:Leads',
        parentName: '::Menu:CRM',
        iconClass: 'fas fa-user-plus',
        order: 1,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Leads',
      },
      {
        path: '/crm/opportunities',
        name: '::Menu:Opportunities',
        parentName: '::Menu:CRM',
        iconClass: 'fas fa-lightbulb',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Opportunities',
      },
      {
        path: '',
        name: '::Menu:Projects',
        iconClass: 'fas fa-project-diagram',
        order: 9,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Projects',
      },
      {
        path: '/projects',
        name: '::Menu:ProjectList',
        iconClass: 'fas fa-list',
        order: 1,
        parentName: '::Menu:Projects',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Projects',
      },
      {
        path: '/assets',
        name: '::Menu:Assets',
        iconClass: 'fas fa-building',
        order: 10,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Assets',
      },
      {
        path: '/assets/repairs',
        name: '::Menu:AssetRepairs',
        parentName: '::Menu:Assets',
        iconClass: 'fas fa-wrench',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Assets',
      },
      {
        path: '/manufacturing/work-orders',
        name: '::Menu:Manufacturing',
        iconClass: 'fas fa-industry',
        order: 11,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Manufacturing',
      },
      {
        path: '/manufacturing/production-plans',
        name: '::Menu:ProductionPlans',
        iconClass: 'fas fa-clipboard-list',
        order: 12,
        parentName: '::Menu:Manufacturing',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.ProductionPlans',
      },
      {
        path: '/manufacturing/bom',
        name: '::Menu:BillOfMaterials',
        iconClass: 'fas fa-sitemap',
        order: 13,
        parentName: '::Menu:Manufacturing',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Manufacturing',
      },
      {
        path: '/manufacturing/settings',
        name: '::Menu:ManufacturingSettings',
        iconClass: 'fas fa-sliders',
        order: 14,
        parentName: '::Menu:Manufacturing',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Manufacturing',
      },
      {
        path: '/sales/installation-notes',
        name: '::Menu:InstallationNotes',
        iconClass: 'fas fa-screwdriver-wrench',
        order: 15,
        parentName: '::Menu:Sales',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.DeliveryNotes',
      },
      {
        path: '/assets/capitalizations',
        name: '::Menu:AssetCapitalizations',
        iconClass: 'fas fa-building-circle-arrow-right',
        order: 3,
        parentName: '::Menu:Assets',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Assets',
      },
      {
        path: '/settings/authorization-rules',
        name: '::Menu:AuthorizationRules',
        iconClass: 'fas fa-shield-halved',
        order: 3,
        parentName: '::Menu:Settings',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.ApprovalWorkflows',
      },
      {
        path: '/settings/notification-logs',
        name: '::Menu:NotificationLogs',
        iconClass: 'fas fa-bell',
        order: 4,
        parentName: '::Menu:Settings',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.AutomationRules',
      },
      {
        path: '/settings/email-templates',
        name: '::Menu:EmailTemplates',
        iconClass: 'fas fa-envelope',
        order: 5,
        parentName: '::Menu:Settings',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.AutomationRules',
      },
      {
        path: '/settings/einvoice',
        name: '::Menu:EInvoiceSettings',
        iconClass: 'fas fa-file-shield',
        order: 6,
        parentName: '::Menu:Settings',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.EInvoice',
      },
      {
        path: '/support/issues',
        name: '::Menu:Support',
        iconClass: 'fas fa-headset',
        order: 13,
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Issues',
      },
      {
        path: '/projects/timesheets',
        name: '::Menu:Timesheets',
        iconClass: 'fas fa-clock',
        order: 14,
        parentName: '::Menu:Projects',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Projects',
      },
      {
        path: '/projects/timesheet-billing',
        name: '::Menu:TimesheetBilling',
        iconClass: 'fas fa-file-invoice-dollar',
        order: 15,
        parentName: '::Menu:Projects',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Projects',
      },
      {
        path: '/hr/leave',
        name: '::Menu:Leave',
        iconClass: 'fas fa-calendar-minus',
        order: 16,
        parentName: '::Menu:HR',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Employees',
      },
      {
        path: '/hr/holiday-lists',
        name: '::Menu:HolidayLists',
        iconClass: 'fas fa-calendar-days',
        order: 16,
        parentName: '::Menu:HR',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Employees',
      },
      {
        path: '/hr/salary-structures',
        name: '::Menu:SalaryStructures',
        iconClass: 'fas fa-money-bill-wave',
        order: 17,
        parentName: '::Menu:HR',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Payroll',
      },
      {
        path: '/hr/leave-allocations',
        name: '::Menu:LeaveAllocations',
        iconClass: 'fas fa-calendar-check',
        order: 18,
        parentName: '::Menu:HR',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Employees.Edit',
      },
      {
        path: '/hr/loans',
        name: '::Menu:Loans',
        iconClass: 'fas fa-hand-holding-dollar',
        order: 19,
        parentName: '::Menu:HR',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Employees',
      },
      {
        path: '/manufacturing/workstations',
        name: '::Menu:Workstations',
        iconClass: 'fas fa-gear',
        order: 5,
        parentName: '::Menu:Manufacturing',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Manufacturing',
      },
      {
        path: '/manufacturing/job-cards',
        name: '::Menu:JobCards',
        iconClass: 'fas fa-id-card',
        order: 6,
        parentName: '::Menu:Manufacturing',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Manufacturing',
      },
      {
        path: '/sales/proforma-invoices',
        name: '::Menu:ProformaInvoices',
        iconClass: 'fas fa-file-invoice',
        order: 14,
        parentName: '::Menu:Sales',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesInvoices',
      },
      {
        path: '/sales/blanket-orders',
        name: '::Menu:BlanketOrders',
        iconClass: 'fas fa-file-contract',
        order: 15,
        parentName: '::Menu:Sales',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesOrders',
      },
      {
        path: '/sales/subscriptions',
        name: '::Menu:Subscriptions',
        iconClass: 'fas fa-rotate',
        order: 16,
        parentName: '::Menu:Sales',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesInvoices',
      },
      {
        path: '/sales/pricing-rules',
        name: '::Menu:PricingRules',
        iconClass: 'fas fa-tags',
        order: 17,
        parentName: '::Menu:Sales',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesInvoices',
      },
      {
        path: '/purchasing/supplier-quotations',
        name: '::Menu:SupplierQuotations',
        iconClass: 'fas fa-file-invoice-dollar',
        order: 8,
        parentName: '::Menu:Purchasing',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.PurchaseOrders',
      },
      {
        path: '/purchasing/subcontracting',
        name: '::Menu:Subcontracting',
        iconClass: 'fas fa-handshake',
        order: 9,
        parentName: '::Menu:Purchasing',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.PurchaseOrders',
      },
      {
        path: '/purchasing/subcontracting-inward',
        name: '::Menu:SubcontractingInwardOrders',
        iconClass: 'fas fa-truck-ramp-box',
        order: 11,
        parentName: '::Menu:Purchasing',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.PurchaseOrders',
      },
      {
        path: '/purchasing/rfq',
        name: '::Menu:RequestForQuotations',
        iconClass: 'fas fa-file-circle-question',
        order: 12,
        parentName: '::Menu:Purchasing',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.PurchaseOrders',
      },
      {
        path: '/purchasing/scorecards',
        name: '::Menu:SupplierScorecards',
        iconClass: 'fas fa-star-half-stroke',
        order: 11,
        parentName: '::Menu:Purchasing',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SupplierScorecards',
      },
      {
        path: '/hr/expense-claims',
        name: '::Menu:ExpenseClaims',
        iconClass: 'fas fa-receipt',
        order: 18,
        parentName: '::Menu:HR',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Employees',
      },
      {
        path: '/hr/salary-slips',
        name: '::Menu:SalarySlips',
        iconClass: 'fas fa-file-invoice-dollar',
        order: 19,
        parentName: '::Menu:HR',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Payroll',
      },
      {
        path: '/sales/dunnings',
        name: '::Menu:Dunnings',
        iconClass: 'fas fa-bell',
        order: 18,
        parentName: '::Menu:Sales',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesInvoices',
      },
      {
        path: '/inventory/serial-numbers',
        name: '::Menu:SerialNumbers',
        iconClass: 'fas fa-barcode',
        order: 7,
        parentName: '::Menu:Inventory',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Items',
      },
      {
        path: '/inventory/batches',
        name: '::Menu:Batches',
        iconClass: 'fas fa-boxes-stacked',
        order: 8,
        parentName: '::Menu:Inventory',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Items',
      },
      {
        path: '/accounting/reports/aging',
        name: '::Menu:AgingReport',
        iconClass: 'fas fa-clock',
        order: 14,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesInvoices',
      },
      {
        path: '/accounting/reports/general-ledger',
        name: '::Menu:GeneralLedger',
        iconClass: 'fas fa-book-open',
        order: 15,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/reports/outstanding',
        name: '::Menu:OutstandingInvoices',
        iconClass: 'fas fa-file-circle-exclamation',
        order: 16,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesInvoices',
      },
      {
        path: '/accounting/reports/party-ledger',
        name: '::Menu:PartyLedger',
        iconClass: 'fas fa-address-book',
        order: 17,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/reports/statement-of-accounts',
        name: '::Menu:StatementOfAccounts',
        iconClass: 'fas fa-file-contract',
        order: 18,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/currency-exchange',
        name: '::Menu:CurrencyExchange',
        iconClass: 'fas fa-exchange-alt',
        order: 19,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/finance-books',
        name: '::Menu:FinanceBooks',
        iconClass: 'fas fa-book-bookmark',
        order: 20,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/bank-transaction-rules',
        name: '::Menu:BankTransactionRules',
        iconClass: 'fas fa-robot',
        order: 21,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.PaymentEntries',
      },
      {
        path: '/accounting/exchange-rate-revaluation',
        name: '::Menu:ExchangeRateRevaluation',
        iconClass: 'fas fa-scale-unbalanced',
        order: 21,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/invoice-discounting',
        name: '::Menu:InvoiceDiscounting',
        iconClass: 'fas fa-percent',
        order: 22,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesInvoices',
      },
      {
        path: '/accounting/fiscal-years',
        name: '::Menu:FiscalYears',
        iconClass: 'fas fa-calendar-days',
        order: 17,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/period-closing',
        name: '::Menu:PeriodClosing',
        iconClass: 'fas fa-lock',
        order: 18,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/month-end-close',
        name: '::Menu:MonthEndClose',
        iconClass: 'fas fa-calendar-check',
        order: 19,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/cost-center-allocations',
        name: '::Menu:CostCenterAllocations',
        iconClass: 'fas fa-diagram-project',
        order: 21,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/report-templates',
        name: '::Menu:ReportTemplates',
        iconClass: 'fas fa-file-lines',
        order: 22,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/account-categories',
        name: '::Menu:AccountCategories',
        iconClass: 'fas fa-layer-group',
        order: 23,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/opening-balance',
        name: '::Menu:OpeningBalance',
        iconClass: 'fas fa-scale-balanced',
        order: 19,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.JournalEntries.Create',
      },
      {
        path: '/accounting/dimensions',
        name: '::Menu:AccountingDimensions',
        iconClass: 'fas fa-cubes',
        order: 20,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/batch-payment',
        name: '::Menu:BatchPayment',
        iconClass: 'fas fa-money-check-dollar',
        order: 20,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.PaymentEntries.Create',
      },
      {
        path: '/accounting/reports/cash-flow',
        name: '::Menu:CashFlowStatement',
        iconClass: 'fas fa-water',
        order: 21,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/accounting/reports/budget-variance',
        name: '::Menu:BudgetVarianceReport',
        iconClass: 'fas fa-chart-column',
        order: 22,
        parentName: '::Menu:Accounting',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.Accounts',
      },
      {
        path: '/sales/reports/gross-profit',
        name: '::Menu:GrossProfitReport',
        iconClass: 'fas fa-chart-line',
        order: 19,
        parentName: '::Menu:Sales',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesInvoices',
      },
      {
        path: '/sales/reports/register',
        name: '::Menu:SalesRegister',
        iconClass: 'fas fa-table-list',
        order: 20,
        parentName: '::Menu:Sales',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesInvoices',
      },
      {
        path: '/sales/reports/item-sales',
        name: '::Menu:ItemSalesSummary',
        iconClass: 'fas fa-chart-column',
        order: 21,
        parentName: '::Menu:Sales',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesInvoices',
      },
      {
        path: '/sales/reports/customer-revenue',
        name: '::Menu:CustomerRevenue',
        iconClass: 'fas fa-users-line',
        order: 22,
        parentName: '::Menu:Sales',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.SalesInvoices',
      },
      {
        path: '/purchasing/reports/register',
        name: '::Menu:PurchaseRegister',
        iconClass: 'fas fa-table-list',
        order: 10,
        parentName: '::Menu:Purchasing',
        layout: eLayoutType.application,
        requiredPolicy: 'MyERP.PurchaseInvoices',
      },
      {
        path: '/settings/company',
        name: '::Menu:CompanySettings',
        iconClass: 'fas fa-gear',
        order: 100,
        layout: eLayoutType.application,
      }]);
}
