import type { AutoGenerateDunningsDto, AutoGenerateDunningsResultDto, CreateDunningDto, DunningDto, SendDunningEmailDto } from './models';
import { RestService, Rest } from '@abp/ng.core';
import type { PagedResultDto } from '@abp/ng.core';
import { Injectable, inject } from '@angular/core';
import type { CompanyFilteredPagedRequestDto } from '../shared/models';

@Injectable({
  providedIn: 'root',
})
export class DunningService {
  private restService = inject(RestService);
  apiName = 'Default';
  

  autoGenerate = (input: AutoGenerateDunningsDto, config?: Partial<Rest.Config>) =>
    this.restService.request<any, AutoGenerateDunningsResultDto>({
      method: 'POST',
      url: '/api/app/dunning/auto-generate',
      body: input,
    },
    { apiName: this.apiName,...config });
  

  cancel = (id: string, config?: Partial<Rest.Config>) =>
    this.restService.request<any, DunningDto>({
      method: 'POST',
      url: `/api/app/dunning/${id}/cancel`,
    },
    { apiName: this.apiName,...config });
  

  create = (input: CreateDunningDto, config?: Partial<Rest.Config>) =>
    this.restService.request<any, DunningDto>({
      method: 'POST',
      url: '/api/app/dunning',
      body: input,
    },
    { apiName: this.apiName,...config });
  

  createFromSalesInvoice = (salesInvoiceId: string, config?: Partial<Rest.Config>) =>
    this.restService.request<any, DunningDto>({
      method: 'POST',
      url: `/api/app/dunning/from-sales-invoice/${salesInvoiceId}`,
    },
    { apiName: this.apiName,...config });
  

  get = (id: string, config?: Partial<Rest.Config>) =>
    this.restService.request<any, DunningDto>({
      method: 'GET',
      url: `/api/app/dunning/${id}`,
    },
    { apiName: this.apiName,...config });
  

  getList = (input: CompanyFilteredPagedRequestDto, config?: Partial<Rest.Config>) =>
    this.restService.request<any, PagedResultDto<DunningDto>>({
      method: 'GET',
      url: '/api/app/dunning',
      params: { companyId: input.companyId, filter: input.filter, status: input.status, fromDate: input.fromDate, toDate: input.toDate, sorting: input.sorting, skipCount: input.skipCount, maxResultCount: input.maxResultCount },
    },
    { apiName: this.apiName,...config });
  

  resolve = (id: string, config?: Partial<Rest.Config>) =>
    this.restService.request<any, DunningDto>({
      method: 'POST',
      url: `/api/app/dunning/${id}/resolve`,
    },
    { apiName: this.apiName,...config });
  

  sendDunningEmail = (id: string, input: SendDunningEmailDto, config?: Partial<Rest.Config>) =>
    this.restService.request<any, void>({
      method: 'POST',
      url: `/api/app/dunning/${id}/send-dunning-email`,
      body: input,
    },
    { apiName: this.apiName,...config });
  

  submit = (id: string, config?: Partial<Rest.Config>) =>
    this.restService.request<any, DunningDto>({
      method: 'POST',
      url: `/api/app/dunning/${id}/submit`,
    },
    { apiName: this.apiName,...config });
}