import type { EntityDto, FullAuditedEntityDto, PagedAndSortedResultRequestDto } from '@abp/ng.core';
import type { CouponType } from './coupon-type.enum';
import type { PricingRuleApplyOn } from './pricing-rule-apply-on.enum';
import type { PricingRuleType } from './pricing-rule-type.enum';
import type { ProformaInvoiceBasis } from './proforma-invoice-basis.enum';
import type { ShippingCalculationMode } from './shipping-calculation-mode.enum';
import type { ShippingRuleType } from './shipping-rule-type.enum';
import type { ProformaInvoiceStatus } from './proforma-invoice-status.enum';
import type { AnalyticsGroupBy } from './analytics-group-by.enum';
import type { AnalyticsPeriodType } from './analytics-period-type.enum';
import type { TrackingBoardStage } from './tracking-board-stage.enum';
import type { PromotionalSchemeApplicableFor } from './promotional-scheme-applicable-for.enum';

export interface ApplyPricingRuleDto {
  itemId?: string | null;
  itemGroupId?: string | null;
  qty?: number;
  amount?: number;
  transactionDate?: string;
}

export interface AutoGenerateDunningsDto {
  companyId?: string;
  asOfDate?: string | null;
  interestRatePerAnnum?: number;
  dunningFeePerCustomer?: number;
}

export interface AutoGenerateDunningsResultDto {
  customersScanned?: number;
  createdCount?: number;
  skippedCount?: number;
  failedCount?: number;
  totalOverdueAmount?: number;
}

export interface BarcodeScanResultDto {
  found?: boolean;
  itemId?: string | null;
  itemCode?: string | null;
  itemName?: string | null;
  rate?: number;
  uom?: string | null;
  barcode?: string | null;
}

export interface BlanketOrderDto extends EntityDto<string> {
  companyId?: string;
  orderNumber?: string;
  orderType?: string;
  partyId?: string;
  partyName?: string | null;
  fromDate?: string;
  toDate?: string;
  status?: number;
  items?: BlanketOrderItemDto[];
  creationTime?: string;
}

export interface BlanketOrderItemDto {
  id?: string;
  itemId?: string;
  itemName?: string | null;
  qty?: number;
  rate?: number;
  orderedQty?: number;
  remainingQty?: number;
}

export interface CouponCodeDto extends EntityDto<string> {
  code?: string;
  couponName?: string;
  couponType?: CouponType;
  pricingRuleId?: string;
  maximumUse?: number;
  used?: number;
  isEnabled?: boolean;
  validFrom?: string | null;
  validUpto?: string | null;
  customerId?: string | null;
  description?: string | null;
}

export interface CreateBlanketOrderDto {
  companyId?: string;
  orderType?: string;
  partyId?: string;
  partyName?: string | null;
  fromDate?: string;
  toDate?: string;
  items?: CreateBlanketOrderItemDto[];
}

export interface CreateBlanketOrderItemDto {
  itemId?: string;
  itemName?: string | null;
  qty?: number;
  rate?: number;
}

export interface CreateCouponCodeDto {
  code?: string | null;
  couponName?: string;
  couponType?: CouponType;
  pricingRuleId?: string;
  companyId?: string | null;
  maximumUse?: number;
  maximumUsePerCustomer?: number;
  validFrom?: string | null;
  validUpto?: string | null;
  customerId?: string | null;
  description?: string | null;
}

export interface CreateDeliveryNoteDto {
  companyId: string;
  customerId: string;
  warehouseId: string;
  postingDate: string;
  salesOrderId?: string | null;
  shippingAddress?: string | null;
  transporter?: string | null;
  trackingNumber?: string | null;
  isReturn?: boolean;
  returnAgainstId?: string | null;
  notes?: string | null;
  items: CreateDeliveryNoteItemDto[];
}

export interface CreateDeliveryNoteItemDto {
  itemId: string;
  description: string;
  quantity: number;
  unitPrice: number;
  taxAmount?: number;
  uom?: string;
  salesOrderItemId?: string | null;
}

export interface CreateDeliveryNoteResultDto {
  deliveryNoteId?: string;
  deliveryNumber?: string;
  itemCount?: number;
  totalAmount?: number;
}

export interface CreateDnFromPendingDto {
  customerId?: string;
  companyId?: string;
  items?: PendingItemSelectionDto[];
}

export interface CreateDunningDto {
  companyId?: string;
  customerId?: string;
  customerName?: string | null;
  postingDate?: string;
  dunningFee?: number;
  interestAmount?: number;
  interestRatePerAnnum?: number;
  overduePayments?: CreateDunningOverdueDto[];
}

export interface CreateDunningOverdueDto {
  salesInvoiceId?: string;
  outstandingAmount?: number;
  dueDate?: string;
  overdueDays?: number;
}

export interface CreateInstallationNoteDto {
  companyId?: string;
  customerId?: string;
  deliveryNoteId?: string;
  installationDate?: string;
  items?: InstallationNoteItemDto[];
}

export interface CreateInvoiceFromDeliveryNotesDto {
  companyId: string;
  customerId: string;
  deliveryNoteIds: string[];
  issueDate?: string | null;
  currencyCode?: string;
  paymentTermsTemplateId?: string | null;
  notes?: string | null;
}

export interface CreateLoyaltyProgramDto {
  companyId?: string;
  name?: string;
  conversionFactor?: number;
  expiryDurationDays?: number;
  expenseAccountId?: string | null;
  costCenterId?: string | null;
  tiers?: LoyaltyProgramTierDto[];
}

export interface CreatePackingSlipDto {
  companyId: string;
  deliveryNoteId: string;
  fromCaseNo?: number;
  toCaseNo?: number;
  grossWeightKg?: number;
  weightUom?: string | null;
  items?: CreatePackingSlipItemDto[];
}

export interface CreatePackingSlipItemDto {
  itemId: string;
  qty?: number;
  netWeight?: number;
  description?: string | null;
  deliveryNoteItemId?: string | null;
}

export interface CreatePosClosingDto {
  companyId?: string;
  posProfileId?: string;
  posOpeningEntryId?: string;
  userId?: string;
  invoices?: CreatePosClosingInvoiceDto[];
  payments?: CreatePosClosingPaymentDto[];
}

export interface CreatePosClosingInvoiceDto {
  posInvoiceId?: string;
  invoiceNumber?: string;
  grandTotal?: number;
}

export interface CreatePosClosingPaymentDto {
  modeOfPaymentId?: string;
  modeName?: string;
  expectedAmount?: number;
  closingAmount?: number;
}

export interface CreatePosInvoiceDto {
  companyId: string;
  customerId?: string | null;
  warehouseId?: string | null;
  items: PosLineItemDto[];
  paymentMethod?: string;
  amountReceived?: number;
}

export interface CreatePosOpeningDto {
  companyId?: string;
  posProfileId?: string;
  userId?: string;
  payments?: CreatePosOpeningPaymentDto[];
}

export interface CreatePosOpeningPaymentDto {
  modeOfPaymentId?: string;
  modeName?: string;
  openingAmount?: number;
}

export interface CreatePricingRuleDto {
  title?: string;
  applicableFor?: string;
  applyOn?: PricingRuleApplyOn;
  applyOnId?: string | null;
  applyOnName?: string | null;
  ruleType?: PricingRuleType;
  discountPercentage?: number;
  discountAmount?: number;
  rate?: number;
  minQty?: number;
  maxQty?: number;
  minAmount?: number;
  maxAmount?: number;
  priority?: number;
  validFrom?: string | null;
  validUpto?: string | null;
  companyId?: string | null;
}

export interface CreateProductBundleDto {
  itemId?: string;
  itemName?: string | null;
  description?: string | null;
  items?: CreateProductBundleItemDto[];
}

export interface CreateProductBundleItemDto {
  componentItemId?: string;
  itemName?: string | null;
  qty?: number;
}

export interface CreateProformaInvoiceDto {
  salesOrderId: string;
  basedOn?: ProformaInvoiceBasis;
  hideItemQty?: boolean;
  items: CreateProformaInvoiceItemDto[];
}

export interface CreateProformaInvoiceItemDto {
  salesOrderItemId: string;
  quantity?: number;
  amount?: number | null;
}

export interface CreateQuotationDto {
  companyId: string;
  customerId: string;
  issueDate: string;
  validUntil?: string | null;
  currencyCode?: string;
  terms?: string | null;
  notes?: string | null;
  items: CreateQuotationItemDto[];
}

export interface CreateQuotationItemDto {
  itemId: string;
  description: string;
  quantity: number;
  unitPrice: number;
  taxAmount?: number;
  uom?: string;
}

export interface CreateSalesInvoiceDto {
  companyId: string;
  customerId: string;
  issueDate: string;
  dueDate?: string | null;
  currencyCode?: string;
  notes?: string | null;
  paymentTermsTemplateId?: string | null;
  isReturn?: boolean;
  returnAgainstId?: string | null;
  isOpening?: boolean;
  costCenterId?: string | null;
  projectId?: string | null;
  updateStock?: boolean;
  warehouseId?: string | null;
  couponCode?: string | null;
  loyaltyPointsToRedeem?: number;
  discountAmount?: number;
  applyDiscountOn?: string | null;
  items: CreateSalesInvoiceItemDto[];
}

export interface CreateSalesInvoiceItemDto {
  itemId: string;
  description: string;
  quantity: number;
  unitPrice: number;
  taxAmount?: number;
  uom?: string;
}

export interface CreateSalesOrderDto {
  companyId: string;
  customerId: string;
  orderDate: string;
  deliveryDate?: string | null;
  customerPoNumber?: string | null;
  currencyCode?: string;
  terms?: string | null;
  notes?: string | null;
  quotationId?: string | null;
  costCenterId?: string | null;
  projectId?: string | null;
  shippingCountry?: string | null;
  couponCode?: string | null;
  loyaltyPointsToRedeem?: number;
  items: CreateSalesOrderItemDto[];
}

export interface CreateSalesOrderItemDto {
  itemId: string;
  description: string;
  quantity: number;
  unitPrice: number;
  taxAmount?: number;
  uom?: string;
  warehouseId?: string | null;
}

export interface CreateSalesPartnerDto {
  name: string;
  partnerType?: number;
  commissionRate?: number;
  territoryId?: string | null;
  website?: string | null;
  description?: string | null;
  referralCode?: string | null;
}

export interface CreateSalesPersonDto {
  name?: string;
  parentSalesPersonId?: string | null;
  isGroup?: boolean;
  employeeId?: string | null;
  commissionRate?: number;
}

export interface CreateSalesTargetDto {
  fiscalYearId?: string | null;
  targetQty?: number;
  targetAmount?: number;
}

export interface CreateShippingRuleDto {
  label?: string;
  companyId?: string;
  accountId?: string;
  costCenterId?: string | null;
  projectId?: string | null;
  calculationMode?: ShippingCalculationMode;
  ruleType?: ShippingRuleType;
  fixedAmount?: number;
  isEnabled?: boolean;
  conditions?: ShippingConditionDto[];
  countries?: string[];
}

export interface CreateSubscriptionDto {
  companyId?: string;
  partyId?: string;
  partyType?: string;
  partyName?: string | null;
  billingInterval?: string;
  billingIntervalCount?: number;
  startDate?: string;
  endDate?: string | null;
  trialPeriodDays?: number;
  plans?: CreateSubscriptionPlanDto[];
}

export interface CreateSubscriptionPlanDto {
  itemId?: string;
  itemName?: string | null;
  qty?: number;
  rate?: number;
}

export interface CreateUpdateCustomerDto {
  companyId: string;
  name: string;
  customerCode?: string | null;
  tin?: string | null;
  registrationNumber?: string | null;
  sstRegistrationNumber?: string | null;
  idType?: string | null;
  idValue?: string | null;
  contactPerson?: string | null;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country?: string | null;
  defaultReceivableAccountId?: string | null;
  isActive?: boolean;
}

export interface CreateUpdatePosProfileDto {
  companyId: string;
  profileName: string;
  warehouseId: string;
  priceListId?: string | null;
  defaultCustomerId?: string | null;
  currencyCode?: string;
  validateStock?: boolean;
  invoiceType?: string;
  isDisabled?: boolean;
  taxTemplateId?: string | null;
  writeOffAccountId?: string | null;
  writeOffCostCenterId?: string | null;
  writeOffLimit?: number;
  postChangeGlEntries?: boolean;
  incomeAccountId?: string | null;
  expenseAccountId?: string | null;
  paymentMethods?: CreateUpdatePosProfilePaymentMethodDto[];
}

export interface CreateUpdatePosProfilePaymentMethodDto {
  modeOfPaymentId: string;
  accountId: string;
  isDefault?: boolean;
}

export interface CustomerDto extends FullAuditedEntityDto<string> {
  companyId?: string;
  name?: string;
  customerCode?: string | null;
  tin?: string | null;
  registrationNumber?: string | null;
  sstRegistrationNumber?: string | null;
  idType?: string | null;
  idValue?: string | null;
  contactPerson?: string | null;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country?: string | null;
  defaultReceivableAccountId?: string | null;
  isActive?: boolean;
}

export interface CustomerRevenueLineDto {
  customerId?: string;
  customerName?: string;
  invoiceCount?: number;
  totalRevenue?: number;
  totalPaid?: number;
  totalOutstanding?: number;
}

export interface CustomerRevenueReportDto {
  items?: CustomerRevenueLineDto[];
  totalRevenue?: number;
  totalOutstanding?: number;
  customerCount?: number;
  fromDate?: string;
  toDate?: string;
}

export interface DeliveryNoteDto extends EntityDto<string> {
  companyId?: string;
  deliveryNumber?: string;
  postingDate?: string;
  customerId?: string;
  customerName?: string | null;
  salesOrderId?: string | null;
  warehouseId?: string;
  shippingAddress?: string | null;
  transporter?: string | null;
  trackingNumber?: string | null;
  currencyCode?: string;
  netTotal?: number;
  taxAmount?: number;
  grandTotal?: number;
  isReturn?: boolean;
  returnAgainstId?: string | null;
  status?: string;
  perBilled?: number;
  items?: DeliveryNoteItemDto[];
}

export interface DeliveryNoteItemDto {
  id?: string;
  itemId?: string;
  description?: string;
  uom?: string;
  quantity?: number;
  unitPrice?: number;
  taxAmount?: number;
  lineTotal?: number;
  billedQty?: number;
  salesOrderItemId?: string | null;
}

export interface DeliveryScheduleEntryDto {
  id?: string;
  salesOrderItemId?: string;
  scheduledDate?: string;
  scheduledQty?: number;
  deliveredQty?: number;
  pendingQty?: number;
  isFullyDelivered?: boolean;
}

export interface DunningDto extends EntityDto<string> {
  companyId?: string;
  customerId?: string;
  customerName?: string | null;
  postingDate?: string;
  dunningLevel?: number;
  totalOutstanding?: number;
  dunningFee?: number;
  interestAmount?: number;
  grandTotal?: number;
  status?: number;
  overduePaymentCount?: number;
  emailSentAt?: string | null;
  emailSentTo?: string | null;
  overduePayments?: DunningOverduePaymentDto[];
}

export interface DunningOverduePaymentDto {
  salesInvoiceId?: string;
  invoiceNumber?: string | null;
  outstandingAmount?: number;
  dueDate?: string;
  overdueDays?: number;
}

export interface EmailPreviewDto {
  subject?: string;
  body?: string;
}

export interface GeneratedInvoiceDto {
  invoiceId?: string;
  invoiceNumber?: string | null;
  grandTotal?: number;
  periodStart?: string | null;
  periodEnd?: string | null;
}

export interface GetCustomerListDto extends PagedAndSortedResultRequestDto {
  filter?: string | null;
}

export interface GetPosProfileListDto extends PagedAndSortedResultRequestDto {
  companyId?: string | null;
  filter?: string | null;
  isDisabled?: boolean | null;
}

export interface GetSalesPartnerListDto extends PagedAndSortedResultRequestDto {
  filter?: string | null;
}

export interface GrossProfitLineDto {
  invoiceId?: string;
  invoiceNumber?: string;
  issueDate?: string;
  customerName?: string | null;
  revenue?: number;
  cost?: number;
  grossProfit?: number;
  grossProfitPercentage?: number;
}

export interface GrossProfitReportDto {
  totalRevenue?: number;
  totalCost?: number;
  grossProfit?: number;
  grossProfitPercentage?: number;
  items?: GrossProfitLineDto[];
}

export interface GrossProfitRequestDto {
  companyId?: string;
  fromDate?: string | null;
  toDate?: string | null;
}

export interface InstallationNoteDto extends EntityDto<string> {
  installationNumber?: string;
  companyId?: string;
  customerId?: string;
  deliveryNoteId?: string;
  installationDate?: string;
  status?: string;
  items?: InstallationNoteItemDto[];
}

export interface InstallationNoteItemDto {
  itemId?: string;
  qty?: number;
  serialNo?: string | null;
}

export interface InvoicePaymentHistoryDto {
  id?: string;
  paymentNumber?: string | null;
  postingDate?: string;
  paymentType?: string | null;
  amount?: number;
}

export interface ItemSalesLineDto {
  itemId?: string;
  itemName?: string;
  totalQty?: number;
  totalRevenue?: number;
  averageRate?: number;
  invoiceCount?: number;
}

export interface ItemSalesReportDto {
  items?: ItemSalesLineDto[];
  totalRevenue?: number;
  totalQty?: number;
  uniqueItems?: number;
  fromDate?: string;
  toDate?: string;
}

export interface LoyaltyBalanceDto {
  customerId?: string;
  programId?: string;
  programName?: string;
  availablePoints?: number;
  currentTier?: string | null;
  redemptionValue?: number;
}

export interface LoyaltyPointEntryDto {
  id?: string;
  points?: number;
  postingDate?: string;
  expiryDate?: string | null;
  invoiceType?: string | null;
  invoiceId?: string | null;
  tierName?: string | null;
  isExpired?: boolean;
  isEarning?: boolean;
}

export interface LoyaltyProgramDto extends EntityDto<string> {
  companyId?: string;
  name?: string;
  conversionFactor?: number;
  expiryDurationDays?: number;
  isEnabled?: boolean;
  expenseAccountId?: string | null;
  costCenterId?: string | null;
  tiers?: LoyaltyProgramTierDto[];
}

export interface LoyaltyProgramTierDto {
  tierName?: string;
  minSpent?: number;
  collectionFactor?: number;
  redemptionFactor?: number;
}

export interface OrderPaymentDto {
  paymentEntryId?: string;
  paymentNumber?: string;
  postingDate?: string;
  paidAmount?: number;
  paymentType?: string;
  referenceNumber?: string | null;
  status?: string;
}

export interface PackingSlipDto extends EntityDto<string> {
  companyId?: string;
  deliveryNoteId?: string;
  deliveryNoteNumber?: string | null;
  fromCaseNo?: number;
  toCaseNo?: number;
  numberOfCases?: number;
  netWeightKg?: number;
  grossWeightKg?: number;
  weightUom?: string | null;
  status?: number;
  creationTime?: string;
  items?: PackingSlipItemDto[];
}

export interface PackingSlipItemDto extends EntityDto<string> {
  itemId?: string;
  itemCode?: string | null;
  itemName?: string | null;
  qty?: number;
  netWeight?: number;
  description?: string | null;
  deliveryNoteItemId?: string | null;
}

export interface PartialDeliveryItemDto {
  salesOrderItemId?: string;
  quantity?: number;
  warehouseId?: string | null;
}

export interface PaymentScheduleDto {
  id?: string;
  dueDate?: string;
  invoicePortion?: number;
  paymentAmount?: number;
  paidAmount?: number;
  outstanding?: number;
  discountType?: string | null;
  discountPercentage?: number;
  discountValidTill?: string | null;
  discountedAmount?: number;
}

export interface PendingDeliveryItemDto {
  salesOrderId?: string;
  orderNumber?: string;
  orderDate?: string;
  deliveryDate?: string | null;
  customerId?: string;
  customerName?: string;
  itemId?: string;
  itemCode?: string;
  itemName?: string;
  orderedQty?: number;
  deliveredQty?: number;
  pendingQty?: number;
  uom?: string;
  rate?: number;
  pendingAmount?: number;
  daysUntilDue?: number;
  isOverdue?: boolean;
  warehouseId?: string | null;
}

export interface PendingDeliveryReportDto {
  asOfDate?: string;
  totalOrders?: number;
  totalItems?: number;
  totalPendingAmount?: number;
  overdueCount?: number;
  overdueAmount?: number;
  items?: PendingDeliveryItemDto[];
}

export interface PendingDeliveryRequestDto {
  companyId?: string;
  asOfDate?: string | null;
  customerId?: string | null;
  itemId?: string | null;
  overdueOnly?: boolean;
}

export interface PendingItemSelectionDto {
  salesOrderId?: string;
  itemId?: string;
  quantity?: number;
}

export interface PlanDimensionsDto {
  costCenterId?: string | null;
}

export interface PosClosingDto extends EntityDto<string> {
  companyId?: string;
  posProfileId?: string;
  postingDate?: string;
  status?: string;
  grandTotal?: number;
  netTotal?: number;
  totalDifference?: number;
  consolidatedSalesInvoiceId?: string | null;
  payments?: PosClosingPaymentDto[];
  invoices?: PosClosingInvoiceDto[];
}

export interface PosClosingInvoiceDto {
  posInvoiceId?: string;
  invoiceNumber?: string;
  grandTotal?: number;
}

export interface PosClosingPaymentDto {
  modeName?: string;
  expectedAmount?: number;
  closingAmount?: number;
  difference?: number;
}

export interface PosExpectedPaymentDto {
  modeOfPaymentId?: string;
  modeName?: string;
  openingAmount?: number;
  invoiceTotal?: number;
  expectedAmount?: number;
}

export interface PosInvoiceDto extends EntityDto<string> {
  invoiceNumber?: string;
  issueDate?: string;
  netTotal?: number;
  taxAmount?: number;
  grandTotal?: number;
  amountReceived?: number;
  change?: number;
  status?: string;
}

export interface PosItemDto {
  id?: string;
  itemCode?: string;
  itemName?: string;
  sellingPrice?: number;
  uom?: string;
  barcode?: string | null;
}

export interface PosItemSearchDto {
  search?: string | null;
  maxResultCount?: number;
}

export interface PosLineItemDto {
  itemId: string;
  description?: string;
  quantity?: number;
  unitPrice?: number;
  taxAmount?: number;
}

export interface PosOpeningDto extends EntityDto<string> {
  companyId?: string;
  posProfileId?: string;
  userId?: string;
  openingDate?: string;
  status?: string;
  totalOpeningAmount?: number;
  posClosingEntryId?: string | null;
  payments?: PosOpeningPaymentDto[];
}

export interface PosOpeningPaymentDto {
  modeOfPaymentId?: string;
  modeName?: string;
  openingAmount?: number;
}

export interface PosProfileDto extends FullAuditedEntityDto<string> {
  companyId?: string;
  profileName?: string;
  warehouseId?: string;
  priceListId?: string | null;
  defaultCustomerId?: string | null;
  currencyCode?: string;
  validateStock?: boolean;
  invoiceType?: string;
  isDisabled?: boolean;
  taxTemplateId?: string | null;
  writeOffAccountId?: string | null;
  writeOffCostCenterId?: string | null;
  writeOffLimit?: number;
  postChangeGlEntries?: boolean;
  incomeAccountId?: string | null;
  expenseAccountId?: string | null;
  paymentMethods?: PosProfilePaymentMethodDto[];
}

export interface PosProfilePaymentMethodDto extends EntityDto<string> {
  posProfileId?: string;
  modeOfPaymentId?: string;
  accountId?: string;
  isDefault?: boolean;
}

export interface PreviewEmailInput {
  documentType?: string;
  templateId?: string | null;
  variables?: Record<string, string>;
}

export interface PricingRuleDto extends EntityDto<string> {
  title?: string;
  applicableFor?: string;
  applyOn?: number;
  applyOnId?: string | null;
  applyOnName?: string | null;
  ruleType?: number;
  discountPercentage?: number;
  discountAmount?: number;
  rate?: number;
  minQty?: number;
  maxQty?: number;
  minAmount?: number;
  maxAmount?: number;
  priority?: number;
  validFrom?: string | null;
  validUpto?: string | null;
  isDisabled?: boolean;
}

export interface PricingRuleResultDto {
  ruleId?: string;
  title?: string;
  ruleType?: number;
  discountPercentage?: number;
  discountAmount?: number;
  rate?: number;
  freeItemId?: string | null;
  freeItemQty?: number;
}

export interface PromotionalSchemeTargetDto {
  targetId?: string;
  targetName?: string | null;
}

export interface PromotionalSchemePartyDto {
  partyId?: string;
  partyName?: string | null;
}

export interface PromotionalSchemePriceDiscountSlabDto {
  rateOrDiscount?: PricingRuleType;
  discountPercentage?: number;
  discountAmount?: number;
  rate?: number;
  minQty?: number;
  maxQty?: number;
  minAmount?: number;
  maxAmount?: number;
  priority?: number;
  warehouseId?: string | null;
  description?: string | null;
  isDisabled?: boolean;
}

export interface PromotionalSchemeProductDiscountSlabDto {
  freeItemId?: string;
  freeQty?: number;
  freeItemRate?: number;
  sameItem?: boolean;
  minQty?: number;
  maxQty?: number;
  minAmount?: number;
  maxAmount?: number;
  priority?: number;
  warehouseId?: string | null;
  description?: string | null;
  isRecursive?: boolean;
  recurseFor?: number;
  roundFreeQty?: boolean;
}

export interface PromotionalSchemeDto extends EntityDto<string> {
  companyId?: string;
  title?: string;
  isDisabled?: boolean;
  applyOn?: PricingRuleApplyOn;
  mixedConditions?: boolean;
  isCumulative?: boolean;
  applyRuleOnOtherItem?: boolean;
  otherApplyOn?: PricingRuleApplyOn | null;
  otherTargetId?: string | null;
  selling?: boolean;
  buying?: boolean;
  applicableFor?: PromotionalSchemeApplicableFor;
  validFrom?: string | null;
  validUpto?: string | null;
  currencyId?: string | null;
  targets?: PromotionalSchemeTargetDto[];
  parties?: PromotionalSchemePartyDto[];
  priceDiscountSlabs?: PromotionalSchemePriceDiscountSlabDto[];
  productDiscountSlabs?: PromotionalSchemeProductDiscountSlabDto[];
  generatedRuleCount?: number;
}

export interface CreateUpdatePromotionalSchemeDto {
  companyId?: string;
  title?: string;
  isDisabled?: boolean;
  applyOn?: PricingRuleApplyOn;
  mixedConditions?: boolean;
  isCumulative?: boolean;
  applyRuleOnOtherItem?: boolean;
  otherApplyOn?: PricingRuleApplyOn | null;
  otherTargetId?: string | null;
  selling?: boolean;
  buying?: boolean;
  applicableFor?: PromotionalSchemeApplicableFor;
  validFrom?: string | null;
  validUpto?: string | null;
  currencyId?: string | null;
  targets?: PromotionalSchemeTargetDto[];
  parties?: PromotionalSchemePartyDto[];
  priceDiscountSlabs?: PromotionalSchemePriceDiscountSlabDto[];
  productDiscountSlabs?: PromotionalSchemeProductDiscountSlabDto[];
}

export interface ProductBundleDto extends EntityDto<string> {
  itemId?: string;
  itemName?: string | null;
  description?: string | null;
  isActive?: boolean;
  items?: ProductBundleItemDto[];
}

export interface ProductBundleItemDto {
  id?: string;
  componentItemId?: string;
  itemName?: string | null;
  qty?: number;
}

export interface ProformaInvoiceDto {
  id?: string;
  proformaNumber?: string;
  proformaDate?: string;
  salesOrderId?: string;
  salesOrderNumber?: string | null;
  customerId?: string;
  customerName?: string | null;
  basedOn?: ProformaInvoiceBasis;
  hideItemQty?: boolean;
  currencyCode?: string | null;
  grandTotal?: number;
  totalQty?: number;
  status?: ProformaInvoiceStatus;
  proformaPdfUrl?: string | null;
  sentOn?: string | null;
  emailedTo?: string | null;
  items?: ProformaInvoiceItemDto[];
}

export interface ProformaInvoiceItemDto {
  id?: string;
  salesOrderItemId?: string;
  itemId?: string;
  itemCode?: string;
  itemName?: string;
  uom?: string | null;
  quantity?: number;
  rate?: number;
  amount?: number;
}

export interface ProformedTotalsDto {
  salesOrderItemId?: string;
  itemCode?: string;
  itemName?: string;
  orderedQty?: number;
  orderedAmount?: number;
  proformedQty?: number;
  proformedAmount?: number;
  remainingQty?: number;
  remainingAmount?: number;
}

export interface QuotationDto extends FullAuditedEntityDto<string> {
  companyId?: string;
  quotationNumber?: string;
  issueDate?: string;
  validUntil?: string | null;
  customerId?: string;
  customerName?: string | null;
  currencyCode?: string;
  netTotal?: number;
  taxAmount?: number;
  grandTotal?: number;
  terms?: string | null;
  notes?: string | null;
  status?: string;
  convertedToSalesOrderId?: string | null;
  perOrdered?: number;
  items?: QuotationItemDto[];
}

export interface QuotationItemDto {
  id?: string;
  itemId?: string;
  description?: string;
  uom?: string;
  quantity?: number;
  unitPrice?: number;
  taxAmount?: number;
  lineTotal?: number;
  orderedQty?: number;
}

export interface RegisterFilterDto {
  companyId?: string;
  fromDate?: string | null;
  toDate?: string | null;
}

export interface RegisterReportDto<T> {
  items?: T[];
  totalNet?: number;
  totalTax?: number;
  totalGrand?: number;
  count?: number;
}

export interface SalesAnalyticsReportDto {
  periodLabels?: string[];
  rows?: SalesAnalyticsRowDto[];
  grandTotal?: number;
  periodTotals?: number[];
}

export interface SalesAnalyticsRequestDto {
  companyId?: string;
  fromDate?: string;
  toDate?: string;
  groupBy?: AnalyticsGroupBy;
  periodType?: AnalyticsPeriodType;
  valueField?: string | null;
}

export interface SalesAnalyticsRowDto {
  entityId?: string;
  entityName?: string;
  periodValues?: number[];
  total?: number;
  growth?: number;
}

export interface SalesCommissionReportDto {
  totalRevenue?: number;
  totalCommission?: number;
  invoiceCount?: number;
  salesPersonCount?: number;
  rows?: SalesPersonCommissionRowDto[];
}

export interface SalesInvoiceDto extends FullAuditedEntityDto<string> {
  companyId?: string;
  invoiceNumber?: string;
  issueDate?: string;
  dueDate?: string | null;
  customerId?: string;
  customerName?: string | null;
  currencyCode?: string;
  exchangeRate?: number;
  netTotal?: number;
  taxAmount?: number;
  grandTotal?: number;
  amountPaid?: number;
  outstandingAmount?: number;
  baseNetTotal?: number;
  baseTaxAmount?: number;
  baseGrandTotal?: number;
  baseOutstandingAmount?: number;
  status?: string;
  eInvoiceStatus?: string | null;
  lhdnUuid?: string | null;
  lhdnLongId?: string | null;
  lhdnSubmissionId?: string | null;
  lhdnSubmittedAt?: string | null;
  isReturn?: boolean;
  returnAgainstId?: string | null;
  amendedFromId?: string | null;
  amendmentIndex?: number;
  debitToAccountId?: string;
  daysOverdue?: number;
  isOverdue?: boolean;
  items?: SalesInvoiceItemDto[];
}

export interface SalesInvoiceItemDto {
  id?: string;
  itemId?: string;
  description?: string;
  uom?: string;
  quantity?: number;
  unitPrice?: number;
  taxAmount?: number;
  lineTotal?: number;
  valuationRate?: number;
  grossProfit?: number;
}

export interface SalesInvoiceListSummaryDto {
  totalOutstanding?: number;
  overdueCount?: number;
  overdueAmount?: number;
  monthlyRevenue?: number;
  monthlyInvoiceCount?: number;
  postedInvoiceCount?: number;
}

export interface SalesOrderDto extends FullAuditedEntityDto<string> {
  companyId?: string;
  orderNumber?: string;
  orderDate?: string;
  deliveryDate?: string | null;
  customerId?: string;
  customerName?: string | null;
  customerPoNumber?: string | null;
  currencyCode?: string;
  netTotal?: number;
  taxAmount?: number;
  grandTotal?: number;
  terms?: string | null;
  notes?: string | null;
  status?: string;
  quotationId?: string | null;
  perDelivered?: number;
  perBilled?: number;
  advancePaid?: number;
  perAdvancePaid?: number;
  firstDeliveryDate?: string | null;
  lastDeliveryDate?: string | null;
  firstBilledDate?: string | null;
  firstPaymentDate?: string | null;
  overdueWarning?: string | null;
  items?: SalesOrderItemDto[];
}

export interface SalesOrderItemDto {
  id?: string;
  itemId?: string;
  description?: string;
  uom?: string;
  quantity?: number;
  unitPrice?: number;
  taxAmount?: number;
  lineTotal?: number;
  deliveredQty?: number;
  billedQty?: number;
  warehouseId?: string | null;
  availableQty?: number;
  isInsufficientStock?: boolean;
}

export interface SalesOrderTrackingBoardCardDto {
  orderId?: string;
  orderNumber?: string;
  customerName?: string;
  grandTotal?: number;
  itemCount?: number;
  perDelivered?: number;
  perBilled?: number;
  stage?: TrackingBoardStage;
  orderDate?: string;
  expectedDeliveryDate?: string;
  isOverdue?: boolean;
  daysOverdue?: number;
}

export interface SalesOrderTrackingBoardDto {
  ordered?: SalesOrderTrackingBoardCardDto[];
  partiallyDelivered?: SalesOrderTrackingBoardCardDto[];
  fullyDelivered?: SalesOrderTrackingBoardCardDto[];
  completed?: SalesOrderTrackingBoardCardDto[];
  totalOrders?: number;
  overdueCount?: number;
  totalValue?: number;
}

export interface SalesPartnerDto extends EntityDto<string> {
  name?: string;
  partnerType?: number;
  commissionRate?: number;
  territoryId?: string | null;
  website?: string | null;
  description?: string | null;
  isEnabled?: boolean;
  referralCode?: string | null;
}

export interface SalesPersonCommissionRowDto {
  salesPersonId?: string;
  salesPersonName?: string;
  invoiceCount?: number;
  totalAllocatedAmount?: number;
  totalCommission?: number;
  commissionRate?: number;
}

export interface SalesPersonDto extends EntityDto<string> {
  name?: string;
  parentSalesPersonId?: string | null;
  isGroup?: boolean;
  employeeId?: string | null;
  commissionRate?: number;
  isEnabled?: boolean;
  targets?: SalesTargetDto[];
}

export interface SalesRegisterLineDto {
  invoiceId?: string;
  invoiceNumber?: string;
  postingDate?: string;
  customerId?: string;
  customerName?: string | null;
  netTotal?: number;
  taxAmount?: number;
  grandTotal?: number;
  amountPaid?: number;
  outstanding?: number;
  isReturn?: boolean;
}

export interface SalesTargetDto {
  fiscalYearId?: string | null;
  targetQty?: number;
  targetAmount?: number;
}

export interface ScanBarcodeInput {
  barcode: string;
  companyId?: string | null;
}

export interface SendDunningEmailDto {
  recipientEmail?: string | null;
  cc?: string | null;
}

export interface SendInvoiceEmailDto {
  invoiceId?: string;
  recipientEmail?: string | null;
  ccEmails?: string[] | null;
  templateId?: string | null;
  attachPdf?: boolean;
}

export interface SendProformaEmailDto {
  recipients: string;
}

export interface SendPurchaseOrderEmailDto {
  documentId?: string;
  recipientEmail?: string | null;
  ccEmails?: string[] | null;
  templateId?: string | null;
  attachPdf?: boolean;
}

export interface SendQuotationEmailDto {
  quotationId?: string;
  recipientEmail?: string | null;
  partyName?: string | null;
  ccEmails?: string[] | null;
  templateId?: string | null;
  attachPdf?: boolean;
}

export interface SendSalesOrderEmailDto {
  documentId?: string;
  recipientEmail?: string | null;
  ccEmails?: string[] | null;
  templateId?: string | null;
  attachPdf?: boolean;
}

export interface SendStatementEmailDto {
  companyId?: string;
  customerId?: string;
  fromDate?: string;
  toDate?: string;
  recipientEmail?: string | null;
  ccEmails?: string[] | null;
  attachPdf?: boolean;
}

export interface ShippingConditionDto {
  fromValue?: number;
  toValue?: number;
  shippingAmount?: number;
}

export interface ShippingRuleDto extends EntityDto<string> {
  label?: string;
  companyId?: string;
  calculationMode?: string;
  ruleType?: string;
  shippingAmount?: number;
  isEnabled?: boolean;
  costCenterId?: string | null;
  projectId?: string | null;
  conditions?: ShippingConditionDto[];
  countries?: string[];
}

export interface SubscriptionDto extends EntityDto<string> {
  companyId?: string;
  partyId?: string;
  partyType?: string;
  partyName?: string | null;
  subscriptionNumber?: string | null;
  billingInterval?: string;
  billingIntervalCount?: number;
  startDate?: string;
  endDate?: string | null;
  currentInvoiceStart?: string | null;
  currentInvoiceEnd?: string | null;
  totalPerInterval?: number;
  status?: number;
  plans?: SubscriptionPlanDto[];
}

export interface SubscriptionPlanDto {
  id?: string;
  itemId?: string;
  itemName?: string | null;
  qty?: number;
  rate?: number;
}

export interface UnbilledDeliveryItemDto {
  deliveryNoteId?: string;
  deliveryNoteNumber?: string;
  deliveryDate?: string;
  itemId?: string;
  itemName?: string | null;
  quantity?: number;
  rate?: number;
  uom?: string | null;
  deliveryNoteItemId?: string;
}

export interface UnbilledOrderItemDto {
  salesOrderId?: string;
  orderNumber?: string;
  orderDate?: string;
  itemId?: string;
  itemName?: string | null;
  quantity?: number;
  rate?: number;
  uom?: string | null;
  salesOrderItemId?: string;
}

export interface UpdateLoyaltyProgramDto {
  name?: string;
  conversionFactor?: number;
  expiryDurationDays?: number;
  isEnabled?: boolean;
  expenseAccountId?: string | null;
  costCenterId?: string | null;
}

export interface UpdateSalesPersonDto {
  parentSalesPersonId?: string | null;
  isGroup?: boolean;
  employeeId?: string | null;
  commissionRate?: number;
}

export interface OrderReceiptDto {
  purchaseReceiptId?: string;
  receiptNumber?: string;
  postingDate?: string;
  status?: string;
  itemCount?: number;
}
