using System;
using System.Collections.Generic;
using System.Linq;
using MyERP.Accounting.Entities;
using Shouldly;
using Xunit;

namespace MyERP.Accounting;

public class ClosingBalanceAndDimensionPostingTests
{
    #region AccountClosingBalance Entity

    [Fact]
    public void AccountClosingBalance_Balance_IsDebitMinusCredit()
    {
        var acb = new AccountClosingBalance(
            Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(),
            new DateTime(2026, 6, 30), "2026-06",
            debit: 50000m, credit: 30000m);

        acb.Balance.ShouldBe(20000m); // Debit balance
    }

    [Fact]
    public void AccountClosingBalance_CreditBalance_IsNegative()
    {
        var acb = new AccountClosingBalance(
            Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(),
            new DateTime(2026, 6, 30), "2026-06",
            debit: 10000m, credit: 45000m);

        acb.Balance.ShouldBe(-35000m); // Credit balance (liability/revenue)
    }

    [Fact]
    public void AccountClosingBalance_ZeroBalances_BalanceIsZero()
    {
        var acb = new AccountClosingBalance(
            Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(),
            new DateTime(2026, 6, 30), "2026-06",
            debit: 0m, credit: 0m);

        acb.Balance.ShouldBe(0m);
    }

    [Fact]
    public void AccountClosingBalance_Update_ChangesBalances()
    {
        var acb = new AccountClosingBalance(
            Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(),
            new DateTime(2026, 6, 30), "2026-06",
            debit: 100m, credit: 50m);

        acb.Update(200m, 75m);

        acb.Debit.ShouldBe(200m);
        acb.Credit.ShouldBe(75m);
        acb.Balance.ShouldBe(125m);
    }

    [Fact]
    public void AccountClosingBalance_WithCostCenter_TracksSeparately()
    {
        var companyId = Guid.NewGuid();
        var accountId = Guid.NewGuid();
        var ccSales = Guid.NewGuid();
        var ccAdmin = Guid.NewGuid();

        var sales = new AccountClosingBalance(Guid.NewGuid(), companyId, accountId,
            new DateTime(2026, 6, 30), "2026-06", 80000m, 0m, ccSales);
        var admin = new AccountClosingBalance(Guid.NewGuid(), companyId, accountId,
            new DateTime(2026, 6, 30), "2026-06", 20000m, 0m, ccAdmin);

        sales.CostCenterId.ShouldBe(ccSales);
        admin.CostCenterId.ShouldBe(ccAdmin);
        (sales.Debit + admin.Debit).ShouldBe(100000m);
    }

    [Fact]
    public void AccountClosingBalance_WithFinanceBook_Scoped()
    {
        var acb = new AccountClosingBalance(
            Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(),
            new DateTime(2026, 6, 30), "2026-06",
            debit: 5000m, credit: 1000m,
            financeBook: "Tax Depreciation");

        acb.FinanceBook.ShouldBe("Tax Depreciation");
    }

    [Fact]
    public void AccountClosingBalance_PcvReference_Tracked()
    {
        var pcvId = Guid.NewGuid();
        var acb = new AccountClosingBalance(
            Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(),
            new DateTime(2026, 6, 30), "2026-06", 100m, 50m);

        acb.PeriodClosingVoucherId = pcvId;
        acb.IsPeriodClosingEntry = true;

        acb.PeriodClosingVoucherId.ShouldBe(pcvId);
        acb.IsPeriodClosingEntry.ShouldBeTrue();
    }

    [Fact]
    public void AccountClosingBalanceService_GetPeriodFromDate_FormatsCorrectly()
    {
        var period = MyERP.Accounting.DomainServices.AccountClosingBalanceService.GetPeriodFromDate(
            new DateTime(2026, 7, 15));

        period.ShouldBe("2026-07");
    }

    [Fact]
    public void AccountClosingBalanceService_GetPeriodFromDate_DecemberEdge()
    {
        var period = MyERP.Accounting.DomainServices.AccountClosingBalanceService.GetPeriodFromDate(
            new DateTime(2026, 12, 31));

        period.ShouldBe("2026-12");
    }

    #endregion

    #region Accounting Dimension Validation

    [Fact]
    public void AccountingDimension_FieldName_AutoGenerated()
    {
        var dim = new AccountingDimension(
            Guid.NewGuid(), "CostCenter", "Cost Center");

        dim.FieldName.ShouldNotBeNullOrWhiteSpace();
    }

    [Fact]
    public void AccountingDimension_IsEnabled_DefaultsTrue()
    {
        var dim = new AccountingDimension(
            Guid.NewGuid(), "Branch", "Branch");

        dim.IsEnabled.ShouldBeTrue();
    }

    [Fact]
    public void AccountingDimension_IsMandatory_DefaultsFalse()
    {
        var dim = new AccountingDimension(
            Guid.NewGuid(), "Territory", "Territory");

        dim.IsMandatory.ShouldBeFalse();
    }

    [Fact]
    public void AccountingDimension_MandatoryEnabled_ReadyForValidation()
    {
        var dim = new AccountingDimension(
            Guid.NewGuid(), "Department", "Department");
        dim.IsMandatory = true;

        dim.IsMandatory.ShouldBeTrue();
        dim.IsEnabled.ShouldBeTrue();
    }

    [Fact]
    public void AccountingDimensionFilter_AllowMode_PermitsListedValues()
    {
        var filterId = Guid.NewGuid();
        var dimId = Guid.NewGuid();
        var accountId = Guid.NewGuid();
        var companyId = Guid.NewGuid();
        var allowedValue = Guid.NewGuid();

        var filter = new AccountingDimensionFilter(
            filterId, dimId, accountId, companyId, isAllowList: true);
        filter.DimensionValueIds = allowedValue.ToString();

        filter.IsValuePermitted(allowedValue).ShouldBeTrue();
        filter.IsValuePermitted(Guid.NewGuid()).ShouldBeFalse(); // Not in allow list
    }

    [Fact]
    public void AccountingDimensionFilter_BlockMode_DeniesListedValues()
    {
        var filterId = Guid.NewGuid();
        var dimId = Guid.NewGuid();
        var accountId = Guid.NewGuid();
        var companyId = Guid.NewGuid();
        var blockedValue = Guid.NewGuid();

        var filter = new AccountingDimensionFilter(
            filterId, dimId, accountId, companyId, isAllowList: false);
        filter.DimensionValueIds = blockedValue.ToString();

        filter.IsValuePermitted(blockedValue).ShouldBeFalse(); // Blocked
        filter.IsValuePermitted(Guid.NewGuid()).ShouldBeTrue(); // Not in block list = allowed
    }

    [Fact]
    public void AccountingDimensionFilter_EmptyAllowList_BlocksAll()
    {
        var filter = new AccountingDimensionFilter(
            Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(),
            isAllowList: true);
        // Empty allow list = nothing is permitted

        filter.IsValuePermitted(Guid.NewGuid()).ShouldBeFalse();
    }

    [Fact]
    public void AccountingDimensionFilter_EmptyBlockList_AllowsAll()
    {
        var filter = new AccountingDimensionFilter(
            Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(),
            isAllowList: false);
        // Empty block list = everything is permitted

        filter.IsValuePermitted(Guid.NewGuid()).ShouldBeTrue();
    }

    #endregion

    #region GlDimensionValue

    [Fact]
    public void GlDimensionValue_LinksToJournalEntryLine()
    {
        var lineId = Guid.NewGuid();
        var dimId = Guid.NewGuid();
        var valueId = Guid.NewGuid();

        var gdv = new GlDimensionValue(Guid.NewGuid(), lineId, dimId, "cost_center_id", valueId);

        gdv.JournalEntryLineId.ShouldBe(lineId);
        gdv.AccountingDimensionId.ShouldBe(dimId);
        gdv.DimensionFieldName.ShouldBe("cost_center_id");
        gdv.DimensionValueId.ShouldBe(valueId);
    }

    [Fact]
    public void GlDimensionValue_TenantIsolation()
    {
        var tenantId = Guid.NewGuid();
        var gdv = new GlDimensionValue(Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), "branch_id", Guid.NewGuid());
        gdv.TenantId = tenantId;

        gdv.TenantId.ShouldBe(tenantId);
    }

    #endregion

    #region FinanceBook Entity

    [Fact]
    public void FinanceBook_CreatesWithRequiredFields()
    {
        var companyId = Guid.NewGuid();
        var fb = new FinanceBook(Guid.NewGuid(), companyId, "Tax Depreciation");

        fb.Name.ShouldBe("Tax Depreciation");
        fb.CompanyId.ShouldBe(companyId);
        fb.IsDefault.ShouldBeFalse();
    }

    [Fact]
    public void FinanceBook_DefaultBook_OnlyOneAllowed()
    {
        var companyId = Guid.NewGuid();
        var defaultBook = new FinanceBook(Guid.NewGuid(), companyId, "Primary Book");
        defaultBook.IsDefault = true;

        var taxBook = new FinanceBook(Guid.NewGuid(), companyId, "Tax Book");
        taxBook.IsDefault = false;

        defaultBook.IsDefault.ShouldBeTrue();
        taxBook.IsDefault.ShouldBeFalse();
        // Uniqueness (only one default per company) enforced at DB/service level
    }

    [Fact]
    public void FinanceBook_TagsOnJournalEntryLine()
    {
        var line = new JournalEntryLine(Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), 1000m, true);
        line.FinanceBook = "IFRS";

        line.FinanceBook.ShouldBe("IFRS");
    }

    [Fact]
    public void FinanceBook_NullFinanceBook_BelongsToDefault()
    {
        var line = new JournalEntryLine(Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), 500m, false);

        // Null finance book = belongs to the default book
        line.FinanceBook.ShouldBeNull();
    }

    #endregion

    #region Posting Dimension Validation Integration

    [Fact]
    public void JournalEntryLine_CostCenterId_IsBuiltInDimension()
    {
        var line = new JournalEntryLine(Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), 1000m, true);
        var ccId = Guid.NewGuid();
        line.CostCenterId = ccId;

        line.CostCenterId.ShouldBe(ccId);
    }

    [Fact]
    public void JournalEntryLine_ProjectId_IsBuiltInDimension()
    {
        var line = new JournalEntryLine(Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), 500m, false);
        var projectId = Guid.NewGuid();
        line.ProjectId = projectId;

        line.ProjectId.ShouldBe(projectId);
    }

    [Fact]
    public void JournalEntry_AllLinesHaveDimensions_PassesValidation()
    {
        // If all lines have the mandatory dimension set, validation passes
        var je = new JournalEntry(Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), DateTime.Today);
        var accId = Guid.NewGuid();
        je.AddLine(accId, 1000m, true);
        je.AddLine(accId, 1000m, false);

        // Set cost center on all lines
        foreach (var line in je.Lines)
            line.CostCenterId = Guid.NewGuid();

        je.Lines.All(l => l.CostCenterId.HasValue).ShouldBeTrue();
    }

    [Fact]
    public void JournalEntry_MissingDimensionOnOneLine_FailsValidation()
    {
        // If one line is missing a mandatory dimension, validation should fail
        var je = new JournalEntry(Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(), DateTime.Today);
        var accId = Guid.NewGuid();
        je.AddLine(accId, 1000m, true);
        je.AddLine(accId, 1000m, false);

        // Only set cost center on first line
        je.Lines[0].CostCenterId = Guid.NewGuid();
        // Second line has no cost center

        je.Lines.Any(l => !l.CostCenterId.HasValue).ShouldBeTrue(); // At least one missing
    }

    #endregion

    #region PCV → Closing Balance Integration

    [Fact]
    public void PeriodClosingVoucher_Submit_ChangesStatus()
    {
        var pcv = new PeriodClosingVoucher(
            Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(),
            new DateTime(2026, 6, 30), new DateTime(2026, 6, 30), Guid.NewGuid());

        // PCV requires at least one entry to submit
        pcv.AddEntry(Guid.NewGuid(), null, 50000m, true);
        pcv.AddEntry(Guid.NewGuid(), null, 50000m, false);

        pcv.Status.ShouldBe(Core.DocumentStatus.Draft);
        pcv.Submit();
        pcv.Status.ShouldBe(Core.DocumentStatus.Submitted);
    }

    [Fact]
    public void PeriodClosingVoucher_Cancel_ChangesStatus()
    {
        var pcv = new PeriodClosingVoucher(
            Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(),
            new DateTime(2026, 6, 30), new DateTime(2026, 6, 30), Guid.NewGuid());

        pcv.AddEntry(Guid.NewGuid(), null, 30000m, true);
        pcv.AddEntry(Guid.NewGuid(), null, 30000m, false);

        pcv.Submit();
        pcv.Cancel();
        pcv.Status.ShouldBe(Core.DocumentStatus.Cancelled);
    }

    [Fact]
    public void PeriodClosingVoucher_HasClosingAccount()
    {
        var closingAccountId = Guid.NewGuid();
        var pcv = new PeriodClosingVoucher(
            Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(),
            new DateTime(2026, 6, 30), new DateTime(2026, 6, 30), closingAccountId);

        pcv.ClosingAccountId.ShouldBe(closingAccountId);
    }

    [Fact]
    public void PeriodClosingVoucher_PostingDateDeterminesPeriod()
    {
        var postingDate = new DateTime(2026, 6, 30);
        var pcv = new PeriodClosingVoucher(
            Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid(),
            postingDate, postingDate, Guid.NewGuid());

        var period = MyERP.Accounting.DomainServices.AccountClosingBalanceService.GetPeriodFromDate(pcv.PostingDate);
        period.ShouldBe("2026-06");
    }

    #endregion
}
