namespace MyERP.Accounting;

/// <summary>
/// Journal Entry voucher types — determines validation rules and GL behavior.
/// Per ERPNext: JE has 18 voucher_type values (gotcha #2614).
/// Each type has specific rules for which accounts can be debited/credited,
/// whether party is mandatory, and how advances are handled.
/// </summary>
public enum JournalEntryVoucherType
{
    /// <summary>General purpose journal entry (manual GL posting).</summary>
    JournalEntry = 0,

    /// <summary>Inter-company journal entry (linked to another company).</summary>
    InterCompanyJournalEntry = 1,

    /// <summary>Bank entry (cash/bank transactions).</summary>
    BankEntry = 2,

    /// <summary>Cash entry (petty cash).</summary>
    CashEntry = 3,

    /// <summary>Credit card entry.</summary>
    CreditCardEntry = 4,

    /// <summary>Debit note (supplier claim).</summary>
    DebitNote = 5,

    /// <summary>Credit note (customer claim).</summary>
    CreditNote = 6,

    /// <summary>Contra entry (bank to cash or vice versa).</summary>
    ContraEntry = 7,

    /// <summary>Excise entry (excise duty).</summary>
    ExciseEntry = 8,

    /// <summary>Write-off entry (bad debt).</summary>
    WriteOffEntry = 9,

    /// <summary>Opening entry (for opening balances on system setup).</summary>
    OpeningEntry = 10,

    /// <summary>Depreciation entry (auto-generated by depreciation scheduler).</summary>
    DepreciationEntry = 11,

    /// <summary>Exchange rate revaluation (unrealized gain/loss).</summary>
    ExchangeRateRevaluation = 12,

    /// <summary>Exchange gain or loss (realized on payment).</summary>
    ExchangeGainOrLoss = 13,

    /// <summary>Deferred revenue recognition.</summary>
    DeferredRevenue = 14,

    /// <summary>Deferred expense recognition.</summary>
    DeferredExpense = 15,

    /// <summary>Reversal entry (auto-generated to reverse another JE).</summary>
    Reversal = 16,

    /// <summary>Period closing entry (P&L closing to retained earnings).</summary>
    PeriodClosing = 17
}
