import { Injectable, inject } from '@angular/core';
import { RestService, Rest } from '@abp/ng.core';
import type { PagedResultDto } from '@abp/ng.core';
import type { WorkOrderDto, CreateWorkOrderDto, GetWorkOrderListDto } from '../../proxy/manufacturing/models';

/**
 * Manual proxy for ManufacturingAppService work-order methods.
 * Uses explicit controller ([RemoteService(false)] — not auto-generated by `abp generate-proxy`).
 */
@Injectable({ providedIn: 'root' })
export class ManufacturingService {
  private restService = inject(RestService);
  apiName = 'Default';

  getWorkOrder = (id: string, config?: Partial<Rest.Config>) =>
    this.restService.request<any, WorkOrderDto>({
      method: 'GET',
      url: `/api/app/manufacturing/work-order/${id}`,
    }, { apiName: this.apiName, ...config });

  getWorkOrderList = (input: GetWorkOrderListDto, config?: Partial<Rest.Config>) =>
    this.restService.request<any, PagedResultDto<WorkOrderDto>>({
      method: 'GET',
      url: '/api/app/manufacturing/work-order',
      params: { ...input },
    }, { apiName: this.apiName, ...config });

  createWorkOrder = (input: CreateWorkOrderDto, config?: Partial<Rest.Config>) =>
    this.restService.request<any, WorkOrderDto>({
      method: 'POST',
      url: '/api/app/manufacturing/work-order',
      body: input,
    }, { apiName: this.apiName, ...config });

  submitWorkOrder = (id: string, config?: Partial<Rest.Config>) =>
    this.restService.request<any, WorkOrderDto>({
      method: 'POST',
      url: `/api/app/manufacturing/work-order/${id}/submit`,
    }, { apiName: this.apiName, ...config });

  startWorkOrder = (id: string, config?: Partial<Rest.Config>) =>
    this.restService.request<any, WorkOrderDto>({
      method: 'POST',
      url: `/api/app/manufacturing/work-order/${id}/start`,
    }, { apiName: this.apiName, ...config });

  recordProduction = (id: string, quantity: number, config?: Partial<Rest.Config>) =>
    this.restService.request<any, WorkOrderDto>({
      method: 'POST',
      url: `/api/app/manufacturing/work-order/${id}/record-production`,
      params: { quantity },
    }, { apiName: this.apiName, ...config });

  stopWorkOrder = (id: string, config?: Partial<Rest.Config>) =>
    this.restService.request<any, WorkOrderDto>({
      method: 'POST',
      url: `/api/app/manufacturing/work-order/${id}/stop`,
    }, { apiName: this.apiName, ...config });

  cancelWorkOrder = (id: string, config?: Partial<Rest.Config>) =>
    this.restService.request<any, WorkOrderDto>({
      method: 'POST',
      url: `/api/app/manufacturing/work-order/${id}/cancel`,
    }, { apiName: this.apiName, ...config });
}
